"""
score_ball.py
=============

Part 1 — Module Foundation

This module defines the immutable data model and configuration used by the
ball-by-ball scoring engine for the Cricket Tournament Manager.

Only foundational structures are defined here:

    • Module imports
    • Type aliases
    • Enumerations
    • Frozen dataclasses
    • Public configuration objects

No scoring logic is implemented in this part.

Future parts will implement:

    • Delivery validation
    • Ball processing
    • Strike rotation
    • Over completion
    • Innings completion
    • Match completion
    • Workbook synchronization
    • Scorecard generation
    • Leaderboard updates

Dependencies
------------
Uses:
    - constants.py
    - formulas.py

Does NOT import:
    - openpyxl
    - workbook.py
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum, IntEnum, auto
from typing import Any, Mapping, Optional, TypeAlias

import constants
import formulas


# =============================================================================
# Type Aliases
# =============================================================================

PlayerId: TypeAlias = str
TeamId: TypeAlias = str
OverNumber: TypeAlias = int
BallNumber: TypeAlias = int
Runs: TypeAlias = int
Wickets: TypeAlias = int
Extras: TypeAlias = int

Metadata: TypeAlias = Mapping[str, Any]


# =============================================================================
# Enumerations
# =============================================================================


class BallType(Enum):
    """Classification of a delivery."""

    LEGAL = auto()
    NO_BALL = auto()
    WIDE = auto()
    DEAD_BALL = auto()


class ExtraType(Enum):
    """Type of extra awarded."""

    NONE = auto()
    BYE = auto()
    LEG_BYE = auto()
    NO_BALL = auto()
    WIDE = auto()
    PENALTY = auto()


class WicketType(Enum):
    """Dismissal method."""

    NONE = auto()
    BOWLED = auto()
    CAUGHT = auto()
    LBW = auto()
    RUN_OUT = auto()
    STUMPED = auto()
    HIT_WICKET = auto()
    RETIRED_OUT = auto()
    TIMED_OUT = auto()
    OBSTRUCTING_FIELD = auto()
    HIT_BALL_TWICE = auto()


class InningsStatus(Enum):
    """Current innings state."""

    NOT_STARTED = auto()
    IN_PROGRESS = auto()
    COMPLETED = auto()


class MatchPhase(Enum):
    """Current match phase."""

    PRE_MATCH = auto()
    FIRST_INNINGS = auto()
    INTERVAL = auto()
    SECOND_INNINGS = auto()
    MATCH_COMPLETE = auto()


class BallOutcome(IntEnum):
    """High-level scoring outcome."""

    NORMAL = 0
    EXTRA = 1
    WICKET = 2
    EXTRA_AND_WICKET = 3


# =============================================================================
# Frozen Dataclasses
# =============================================================================


@dataclass(frozen=True, slots=True)
class BallInput:
    """
    Immutable representation of one delivery before processing.
    """

    innings: int
    over: OverNumber
    ball: BallNumber

    striker: PlayerId
    non_striker: PlayerId
    bowler: PlayerId

    batting_team: TeamId
    bowling_team: TeamId

    runs_off_bat: Runs = 0
    extra_runs: Extras = 0

    ball_type: BallType = BallType.LEGAL
    extra_type: ExtraType = ExtraType.NONE
    wicket_type: WicketType = WicketType.NONE

    metadata: Metadata = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class BallResult:
    """
    Immutable processed result of one delivery.

    Later parts will populate these fields after validation.
    """

    legal_delivery: bool

    total_runs: Runs

    batter_runs: Runs

    extras: Extras

    wickets: Wickets

    outcome: BallOutcome

    commentary: str = ""


@dataclass(frozen=True, slots=True)
class BatterState:
    """
    Snapshot of batter state.
    """

    player: PlayerId

    runs: Runs = 0

    balls: int = 0

    fours: int = 0

    sixes: int = 0

    on_strike: bool = False

    dismissed: bool = False


@dataclass(frozen=True, slots=True)
class BowlerState:
    """
    Snapshot of bowler statistics.
    """

    player: PlayerId

    legal_balls: int = 0

    maidens: int = 0

    runs_conceded: Runs = 0

    wickets: Wickets = 0


@dataclass(frozen=True, slots=True)
class InningsState:
    """
    Immutable snapshot of innings state.

    This object represents the score before or after a delivery.
    """

    innings_number: int

    batting_team: TeamId

    bowling_team: TeamId

    status: InningsStatus

    total_runs: Runs = 0

    wickets: Wickets = 0

    legal_balls: int = 0

    striker: Optional[BatterState] = None

    non_striker: Optional[BatterState] = None

    bowler: Optional[BowlerState] = None


@dataclass(frozen=True, slots=True)
class ScoreEvent:
    """
    Scoring event generated by one delivery.
    """

    batter_runs: Runs

    extras: Extras

    total_runs: Runs

    legal_delivery: bool


@dataclass(frozen=True, slots=True)
class WicketEvent:
    """
    Wicket information generated by a delivery.
    """

    wicket_type: WicketType

    player_out: Optional[PlayerId]

    credited_to_bowler: bool = True


@dataclass(frozen=True, slots=True)
class ExtraEvent:
    """
    Extra information awarded on a delivery.
    """

    extra_type: ExtraType

    runs: Extras

    counts_as_ball: bool


@dataclass(frozen=True, slots=True)
class ScoreEngineConfig:
    """
    Immutable scoring engine configuration.

    Values default to tournament constants where available.
    """

    balls_per_over: int = getattr(constants, "BALLS_PER_OVER", 6)

    maximum_wickets: int = getattr(constants, "MAX_WICKETS", 10)

    enable_super_over: bool = getattr(constants, "ENABLE_SUPER_OVER", False)

    allow_retired_hurt_return: bool = True

    formulas_module: Any = formulas

# =============================================================================
# Validation Helpers
# =============================================================================

def validate_runs(runs: int) -> None:
    """
    Validate runs scored from the bat.

    Raises
    ------
    ValueError
        If the supplied run value is invalid.
    """
    if not isinstance(runs, int):
        raise TypeError("Runs must be an integer.")

    if runs < 0:
        raise ValueError("Runs cannot be negative.")

    max_runs = getattr(constants, "MAX_RUNS_OFF_BAT", 6)
    if runs > max_runs:
        raise ValueError(
            f"Runs cannot exceed {max_runs}."
        )


def validate_extra_type(extra_type: ExtraType) -> None:
    """
    Validate an extra type.
    """
    if not isinstance(extra_type, ExtraType):
        raise TypeError("Invalid ExtraType.")

    allowed = getattr(constants, "EXTRA_TYPES", None)

    if allowed is not None:
        if extra_type.name not in allowed and extra_type.value not in allowed:
            raise ValueError(
                f"Unsupported extra type: {extra_type.name}"
            )


def validate_dismissal_type(dismissal: WicketType) -> None:
    """
    Validate dismissal type.
    """
    if not isinstance(dismissal, WicketType):
        raise TypeError("Invalid WicketType.")

    allowed = getattr(constants, "DISMISSAL_TYPES", None)

    if allowed is not None:
        if dismissal.name not in allowed and dismissal.value not in allowed:
            raise ValueError(
                f"Unsupported dismissal type: {dismissal.name}"
            )


def validate_ball_number(over: int, ball: int) -> None:
    """
    Validate over and ball numbering.
    """
    if over < 0:
        raise ValueError("Over number cannot be negative.")

    if ball < 1:
        raise ValueError("Ball number must be at least 1.")

    balls_per_over = getattr(constants, "BALLS_PER_OVER", 6)

    # Illegal deliveries (wide/no-ball) may temporarily exceed the legal
    # ball count, therefore allow one additional delivery by default.
    max_ball = balls_per_over + 1

    if ball > max_ball:
        raise ValueError(
            f"Ball number cannot exceed {max_ball}."
        )


def validate_batter_bowler(
    striker: PlayerId,
    non_striker: PlayerId,
    bowler: PlayerId,
) -> None:
    """
    Validate participating players.
    """
    if not striker:
        raise ValueError("Striker is required.")

    if not non_striker:
        raise ValueError("Non-striker is required.")

    if not bowler:
        raise ValueError("Bowler is required.")

    if striker == non_striker:
        raise ValueError(
            "Striker and non-striker cannot be the same player."
        )

    if striker == bowler:
        raise ValueError(
            "Bowler cannot be the striker."
        )

    if non_striker == bowler:
        raise ValueError(
            "Bowler cannot be the non-striker."
        )


def validate_innings_state(state: InningsState) -> None:
    """
    Validate an innings snapshot.
    """
    if state.total_runs < 0:
        raise ValueError("Total runs cannot be negative.")

    if state.wickets < 0:
        raise ValueError("Wickets cannot be negative.")

    max_wickets = getattr(constants, "MAX_WICKETS", 10)

    if state.wickets > max_wickets:
        raise ValueError(
            f"Wickets cannot exceed {max_wickets}."
        )

    if state.legal_balls < 0:
        raise ValueError("Legal ball count cannot be negative.")

    if (
        state.striker is not None
        and state.non_striker is not None
        and state.striker.player == state.non_striker.player
    ):
        raise ValueError(
            "Striker and non-striker cannot reference the same batter."
        )


def validate_delivery_input(ball: BallInput) -> None:
    """
    Perform complete validation of a delivery before scoring.
    """
    validate_runs(ball.runs_off_bat)

    validate_extra_type(ball.extra_type)

    validate_dismissal_type(ball.wicket_type)

    validate_ball_number(ball.over, ball.ball)

    validate_batter_bowler(
        ball.striker,
        ball.non_striker,
        ball.bowler,
    )

    if ball.extra_runs < 0:
        raise ValueError("Extra runs cannot be negative.")

    legal = set(getattr(constants, "LEGAL_DELIVERIES", {"LEGAL"}))
    illegal = set(getattr(constants, "ILLEGAL_DELIVERIES", {"NO_BALL", "WIDE"}))

    if ball.ball_type.name not in legal.union(illegal):
        raise ValueError(
            f"Unsupported ball type: {ball.ball_type.name}"
        )

    if (
        ball.ball_type is BallType.LEGAL
        and ball.extra_type in (ExtraType.NO_BALL, ExtraType.WIDE)
    ):
        raise ValueError(
            "NO_BALL or WIDE extras require a corresponding illegal delivery."
        )

    if (
        ball.ball_type in (BallType.NO_BALL, BallType.WIDE)
        and ball.extra_type is ExtraType.NONE
    ):
        raise ValueError(
            "Illegal deliveries must specify an appropriate extra type."
        )

# =============================================================================
# Delivery Classification Helpers
# =============================================================================

def is_legal_ball(ball: BallInput) -> bool:
    """
    Return True if the delivery counts as a legal ball.

    Legal deliveries increment the legal ball count for the over.
    """
    legal = set(getattr(constants, "LEGAL_DELIVERIES", {"LEGAL"}))
    return ball.ball_type.name in legal


def is_wide(ball: BallInput) -> bool:
    """
    Return True if the delivery is a wide.
    """
    return (
        ball.ball_type is BallType.WIDE
        or ball.extra_type is ExtraType.WIDE
    )


def is_no_ball(ball: BallInput) -> bool:
    """
    Return True if the delivery is a no-ball.
    """
    return (
        ball.ball_type is BallType.NO_BALL
        or ball.extra_type is ExtraType.NO_BALL
    )


def is_bye(ball: BallInput) -> bool:
    """
    Return True if the delivery resulted in byes.
    """
    return ball.extra_type is ExtraType.BYE


def is_leg_bye(ball: BallInput) -> bool:
    """
    Return True if the delivery resulted in leg byes.
    """
    return ball.extra_type is ExtraType.LEG_BYE


def is_bowling_extra(ball: BallInput) -> bool:
    """
    Return True if the extra is charged to the bowler.

    Bowling extras:
        • Wide
        • No-ball
    """
    return is_wide(ball) or is_no_ball(ball)


def is_fielding_extra(ball: BallInput) -> bool:
    """
    Return True if the extra originates from fielding
    rather than bowling.

    Fielding extras:
        • Bye
        • Leg bye
    """
    return is_bye(ball) or is_leg_bye(ball)


def counts_for_batter(ball: BallInput) -> bool:
    """
    Return True if runs from this delivery are credited
    to the batter.

    Runs are *not* credited for:
        • Byes
        • Leg byes
    """
    return not (is_bye(ball) or is_leg_bye(ball))


def counts_for_bowler(ball: BallInput) -> bool:
    """
    Return True if runs are charged against the bowler.

    Charged to bowler:
        • Runs off the bat
        • Wides
        • No-balls

    Not charged:
        • Byes
        • Leg byes
    """
    return not is_fielding_extra(ball)


def counts_for_team(ball: BallInput) -> bool:
    """
    Every valid scoring event contributes to the team total.

    Dead-ball handling is introduced in later parts.
    """
    return ball.ball_type is not BallType.DEAD_BALL


def counts_as_wicket(ball: BallInput) -> bool:
    """
    Return True if a wicket fell on the delivery.
    """
    return ball.wicket_type is not WicketType.NONE


def bowler_gets_wicket(ball: BallInput) -> bool:
    """
    Return True if the wicket is credited to the bowler.

    Bowler credited:
        • Bowled
        • Caught
        • LBW
        • Stumped
        • Hit wicket

    Not credited:
        • Run out
        • Retired out
        • Timed out
        • Obstructing the field
        • Hit ball twice
    """
    return ball.wicket_type in {
        WicketType.BOWLED,
        WicketType.CAUGHT,
        WicketType.LBW,
        WicketType.STUMPED,
        WicketType.HIT_WICKET,
    }


# =============================================================================
# Score Calculation Helpers
# =============================================================================

def calculate_delivery_runs(ball: BallInput) -> Runs:
    """
    Calculate the total team runs scored from a delivery.

    Total runs =
        batter runs
        + extras

    Dead balls contribute no runs unless future Laws/tournament rules specify
    otherwise.
    """
    if ball.ball_type is BallType.DEAD_BALL:
        return 0

    return calculate_batter_runs(ball) + calculate_extras(ball)


def calculate_batter_runs(ball: BallInput) -> Runs:
    """
    Calculate runs credited to the batter.

    Batter runs are not awarded for:
        * Byes
        * Leg byes

    Runs from no-balls (off the bat) are still credited to the batter.
    """
    if not counts_for_batter(ball):
        return 0

    return ball.runs_off_bat


def calculate_bowler_runs_conceded(ball: BallInput) -> Runs:
    """
    Calculate runs charged to the bowler.

    Charged:
        * Runs scored from the bat
        * Wides
        * No-ball penalties

    Not charged:
        * Byes
        * Leg byes
    """
    if not counts_for_bowler(ball):
        return 0

    runs = ball.runs_off_bat

    if is_bowling_extra(ball):
        runs += ball.extra_runs

    return runs


def calculate_extras(ball: BallInput) -> Extras:
    """
    Calculate extras awarded to the batting side.

    This value is added to the team score but may or may not be charged
    to the bowler depending on the type of extra.
    """
    return ball.extra_runs


def calculate_legal_ball_increment(ball: BallInput) -> int:
    """
    Return the increment for the legal ball counter.

    Returns
    -------
    int
        1 for legal deliveries, otherwise 0.
    """
    return 1 if is_legal_ball(ball) else 0


def calculate_next_over_ball(
    current_over: int,
    current_ball: int,
    *,
    legal_increment: int,
) -> tuple[int, int]:
    """
    Calculate the next over/ball position after processing a delivery.

    Parameters
    ----------
    current_over:
        Zero-based over number.

    current_ball:
        Current legal ball number within the over (1..balls_per_over).

    legal_increment:
        Value returned by ``calculate_legal_ball_increment()``.

    Returns
    -------
    tuple[int, int]
        (next_over, next_ball)

    Notes
    -----
    Illegal deliveries do not advance the legal ball count.
    """
    balls_per_over = getattr(constants, "BALLS_PER_OVER", 6)

    if legal_increment == 0:
        return current_over, current_ball

    next_ball = current_ball + 1
    next_over = current_over

    if next_ball > balls_per_over:
        next_over += 1
        next_ball = 1

    return next_over, next_ball


def calculate_required_after_delivery(
    target: Optional[int],
    current_score: int,
) -> Optional[int]:
    """
    Calculate runs still required after a completed delivery.

    Parameters
    ----------
    target:
        Target score (not runs-to-win). If None, returns None.

    current_score:
        Team score after the delivery.

    Returns
    -------
    Optional[int]
        Runs still required to win.

        Returns 0 once the target has been achieved.
    """
    if target is None:
        return None

    required = target - current_score

    return max(required, 0)

    # ------------------------------------------------------------------
    # Delivery calculations
    # ------------------------------------------------------------------

    team_runs = calculate_delivery_runs(ball_input)

    batter_runs = calculate_batter_runs(ball_input)

    bowler_runs_conceded = calculate_bowler_runs_conceded(ball_input)

    extras = calculate_extras(ball_input)

    legal_ball_increment = calculate_legal_ball_increment(ball_input)

    legal_ball = bool(legal_ball_increment)

    boundary_four = batter_runs == 4

    boundary_six = batter_runs == 6

    dismissal = ball_input.dismissal

    wicket_fell = dismissal is not None

    if wicket_fell:
        dismissed_player = striker

    # ------------------------------------------------------------------
    # Populate BallResult
    # ------------------------------------------------------------------

    result.team_runs = team_runs
    result.batter_runs = batter_runs
    result.extras = extras
    result.bowler_runs = bowler_runs_conceded

    result.legal_delivery = legal_ball
    result.legal_ball = legal_ball
    result.legal_ball_increment = legal_ball_increment

    result.boundary_four = boundary_four
    result.boundary_six = boundary_six

    result.dismissal = dismissal
    result.wicket = wicket_fell
    result.dismissed_player = dismissed_player

    result.extra_type = ball_input.extra_type
    result.extra_runs = extras

    result.ball_input = ball_input


    # ------------------------------------------------------------------
    # Batter statistics
    # ------------------------------------------------------------------

    # Credit batter runs.
    #
    # calculate_batter_runs() already accounts for:
    #   * wides            -> 0
    #   * byes             -> 0
    #   * leg byes         -> 0
    #   * no-ball scoring  -> batter receives only the bat component
    #
    striker.runs += batter_runs

    # Only legal deliveries count as a batter ball faced.
    if legal_ball:
        striker.balls += 1

    # Boundary tracking.
    if boundary_four:
        striker.fours += 1

    if boundary_six:
        striker.sixes += 1

    # Maintain strike rate if the model stores it.
    if hasattr(striker, "strike_rate"):
        if striker.balls > 0:
            striker.strike_rate = (
                striker.runs * 100.0
            ) / striker.balls
        else:
            striker.strike_rate = 0.0

    # Record dismissal status.
    if wicket_fell and dismissed_player is striker:
        if hasattr(striker, "dismissed"):
            striker.dismissed = True

        if hasattr(striker, "is_out"):
            striker.is_out = True

        if hasattr(striker, "dismissal"):
            striker.dismissal = dismissal

        if hasattr(striker, "dismissal_type"):
            striker.dismissal_type = dismissal

        if hasattr(striker, "how_out"):
            striker.how_out = dismissal


    # ------------------------------------------------------------------
    # Bowler statistics
    # ------------------------------------------------------------------

    # Only legal deliveries count towards the bowler's ball count.
    if legal_ball:
        bowler.balls += 1

    # Runs conceded are determined by calculate_bowler_runs_conceded(),
    # which correctly excludes byes and leg byes while including:
    #   * batter runs
    #   * wides
    #   * no-ball penalties
    bowler.runs_conceded += bowler_runs_conceded

    # Prepare maiden-over tracking.
    #
    # Actual maiden determination is deferred until over completion,
    # where the total runs conceded in the completed over are known.
    if hasattr(bowler, "_current_over_runs"):
        bowler._current_over_runs += bowler_runs_conceded

    if hasattr(bowler, "_current_over_legal_balls") and legal_ball:
        bowler._current_over_legal_balls += 1

    # Credit wickets only for dismissals attributable to the bowler.
    if wicket_fell:
        bowler_credit = True

        # Common dismissal types that do NOT count as a bowler wicket.
        if dismissal in {
            DismissalType.RUN_OUT,
            DismissalType.RETIRED_OUT,
            DismissalType.RETIRED_HURT,
            DismissalType.OBSTRUCTING_THE_FIELD,
            DismissalType.TIMED_OUT,
            DismissalType.HIT_THE_BALL_TWICE,
        }:
            bowler_credit = False

        if bowler_credit:
            bowler.wickets += 1


    # ------------------------------------------------------------------
    # Team score and extras
    # ------------------------------------------------------------------

    # Innings totals.
    innings.total_runs += team_runs

    if wicket_fell:
        innings.wickets += 1

    # Legal delivery count.
    innings.legal_balls += legal_ball_increment

    # Maintain over-level running total if present.
    if hasattr(innings, "current_over_runs"):
        innings.current_over_runs += team_runs

    # ------------------------------------------------------------------
    # Extras breakdown
    # ------------------------------------------------------------------

    if ball_input.extra_type == ExtraType.WIDE:
        innings.wides += extras

    elif ball_input.extra_type == ExtraType.NO_BALL:
        innings.no_balls += extras

    elif ball_input.extra_type == ExtraType.BYE:
        innings.byes += extras

    elif ball_input.extra_type == ExtraType.LEG_BYE:
        innings.leg_byes += extras

    # Aggregate innings extras.
    if hasattr(innings, "extras"):
        innings.extras += extras

    # Batting team aggregates.
    if hasattr(batting_team, "runs"):
        batting_team.runs += team_runs

    if hasattr(batting_team, "wickets"):
        batting_team.wickets = innings.wickets

    if hasattr(batting_team, "extras"):
        batting_team.extras += extras

    if hasattr(batting_team, "byes"):
        batting_team.byes = getattr(innings, "byes", 0)

    if hasattr(batting_team, "leg_byes"):
        batting_team.leg_byes = getattr(innings, "leg_byes", 0)

    if hasattr(batting_team, "wides"):
        batting_team.wides = getattr(innings, "wides", 0)

    if hasattr(batting_team, "no_balls"):
        batting_team.no_balls = getattr(innings, "no_balls", 0)

    # Bowling team aggregates.
    if hasattr(bowling_team, "runs_conceded"):
        bowling_team.runs_conceded += team_runs

    if hasattr(bowling_team, "extras_conceded"):
        bowling_team.extras_conceded += extras

    if hasattr(bowling_team, "wides"):
        bowling_team.wides = getattr(innings, "wides", 0)

    if hasattr(bowling_team, "no_balls"):
        bowling_team.no_balls = getattr(innings, "no_balls", 0)

    # ------------------------------------------------------------------
    # Populate BallResult cumulative fields
    # ------------------------------------------------------------------

    result.innings_runs = innings.total_runs
    result.innings_wickets = innings.wickets
    result.innings_extras = getattr(innings, "extras", extras)

    result.total_runs = innings.total_runs
    result.total_wickets = innings.wickets

    result.wides = getattr(innings, "wides", 0)
    result.no_balls = getattr(innings, "no_balls", 0)
    result.byes = getattr(innings, "byes", 0)
    result.leg_byes = getattr(innings, "leg_byes", 0)

    result.current_over_runs = getattr(
        innings,
        "current_over_runs",
        None,
    )


    # ------------------------------------------------------------------
    # Strike rotation
    # ------------------------------------------------------------------

    rotate_strike = False

    # Batter runs.
    if batter_runs % 2 == 1:
        rotate_strike = not rotate_strike

    # Byes / Leg-byes.
    #
    # The physical running between the wickets determines strike for these
    # deliveries, even though the runs are not credited to the batter.
    if ball_input.extra_type in (
        ExtraType.BYE,
        ExtraType.LEG_BYE,
    ):
        if extras % 2 == 1:
            rotate_strike = not rotate_strike

    # Swap batters immediately if required after the delivery.
    if rotate_strike:
        new_striker, new_non_striker = (
            new_non_striker,
            new_striker,
        )

    # Completed over.
    #
    # After six legal deliveries the strike changes once more before the
    # next over begins.
    over_completed = (
        legal_ball
        and innings.legal_balls > 0
        and innings.legal_balls % BALLS_PER_OVER == 0
    )

    if over_completed:
        new_striker, new_non_striker = (
            new_non_striker,
            new_striker,
        )

    # Wicket handling.
    #
    # Actual incoming batter selection is performed by the batting-order
    # logic in a later stage. Here we only preserve the existing references
    # until the replacement batter is supplied.
    if wicket_fell:
        if dismissed_player is striker:
            new_striker = striker
        elif dismissed_player is non_striker:
            new_non_striker = non_striker

    # Preserve updated batting references.
    striker = new_striker
    non_striker = new_non_striker

    # Record transition information.
    result.rotate_strike = rotate_strike
    result.over_completed = over_completed
    result.striker = striker
    result.non_striker = non_striker


    # ------------------------------------------------------------------
    # Over progression
    # ------------------------------------------------------------------

    # Only legal deliveries advance the over.
    if legal_ball:
        completed_overs = innings.legal_balls // BALLS_PER_OVER
        balls_into_over = innings.legal_balls % BALLS_PER_OVER
    else:
        # Wides and no-balls do not advance the legal delivery count.
        completed_overs = getattr(
            innings,
            "completed_overs",
            innings.legal_balls // BALLS_PER_OVER,
        )
        balls_into_over = innings.legal_balls % BALLS_PER_OVER

    # Maintain completed overs if tracked explicitly.
    if hasattr(innings, "completed_overs"):
        innings.completed_overs = completed_overs

    # Balls remaining in the current over.
    balls_remaining = BALLS_PER_OVER - balls_into_over
    if balls_remaining == BALLS_PER_OVER:
        balls_remaining = 0

    if hasattr(innings, "balls_remaining_in_over"):
        innings.balls_remaining_in_over = balls_remaining

    # Current over notation (e.g. 12.3).
    current_over = f"{completed_overs}.{balls_into_over}"

    if hasattr(innings, "current_over"):
        innings.current_over = current_over

    if hasattr(innings, "over_notation"):
        innings.over_notation = current_over

    # End-of-over processing.
    #
    # Wides and no-balls never complete an over because they are not legal
    # deliveries.
    if legal_ball and balls_into_over == 0:
        over_completed = True

        # The strike changes at the end of every completed over.
        striker, non_striker = non_striker, striker

        # Reset running over total if maintained.
        if hasattr(innings, "current_over_runs"):
            innings.current_over_runs = 0

        # Maiden-over determination will be finalized in a later part.
    else:
        over_completed = False

    # ------------------------------------------------------------------
    # BallResult over information
    # ------------------------------------------------------------------

    result.legal_balls = innings.legal_balls
    result.completed_overs = completed_overs
    result.balls_into_over = balls_into_over
    result.balls_remaining = balls_remaining
    result.current_over = current_over
    result.over_completed = over_completed


    # ------------------------------------------------------------------
    # Wicket handling
    # ------------------------------------------------------------------

    if wicket_fell:
        # Ensure innings wicket tally is synchronized.
        innings.wickets = max(innings.wickets, 1)

        # Mark dismissal on the outgoing batter.
        if dismissed_player is not None:
            if hasattr(dismissed_player, "dismissed"):
                dismissed_player.dismissed = True

            if hasattr(dismissed_player, "is_out"):
                dismissed_player.is_out = True

            if hasattr(dismissed_player, "dismissal"):
                dismissed_player.dismissal = dismissal

            if hasattr(dismissed_player, "dismissal_type"):
                dismissed_player.dismissal_type = dismissal

            if hasattr(dismissed_player, "how_out"):
                dismissed_player.how_out = dismissal

            if hasattr(dismissed_player, "bowler"):
                dismissed_player.bowler = bowler

        # Determine whether the wicket is credited to the bowler.
        bowler_gets_wicket = dismissal in {
            DismissalType.BOWLED,
            DismissalType.CAUGHT,
            DismissalType.LBW,
            DismissalType.STUMPED,
            DismissalType.HIT_WICKET,
        }

        # Handled the ball (if supported by the Laws version used).
        if hasattr(DismissalType, "HANDLED_THE_BALL"):
            if dismissal == DismissalType.HANDLED_THE_BALL:
                bowler_gets_wicket = False

        # Non-bowler dismissals.
        if dismissal in {
            DismissalType.RUN_OUT,
            DismissalType.OBSTRUCTING_THE_FIELD,
            DismissalType.RETIRED_OUT,
        }:
            bowler_gets_wicket = False

        # Synchronize bowler wicket count.
        if bowler_gets_wicket:
            expected_wickets = getattr(result, "bowler_wickets", bowler.wickets)
            result.bowler_wickets = expected_wickets
        else:
            result.bowler_wickets = bowler.wickets

        # Placeholder for batting-order logic.
        incoming_batter = None

        if dismissed_player is striker:
            new_striker = incoming_batter
        elif dismissed_player is non_striker:
            new_non_striker = incoming_batter

        # Populate dismissal information.
        result.wicket = True
        result.wicket_fell = True
        result.dismissal = dismissal
        result.dismissal_type = dismissal
        result.dismissed_player = dismissed_player
        result.incoming_batter = incoming_batter
        result.total_wickets = innings.wickets


    # ------------------------------------------------------------------
    # Innings completion
    # ------------------------------------------------------------------

    innings_completed = False

    completion_reason = None

    # --------------------------------------------------------------
    # All out
    # --------------------------------------------------------------

    if innings.wickets >= innings.max_wickets:
        innings_completed = True
        completion_reason = InningsCompletionReason.ALL_OUT

    # --------------------------------------------------------------
    # Overs exhausted
    # --------------------------------------------------------------

    elif innings.legal_balls >= (
        innings.allocated_overs * BALLS_PER_OVER
    ):
        innings_completed = True
        completion_reason = InningsCompletionReason.OVERS_COMPLETED

    # --------------------------------------------------------------
    # Successful chase
    # --------------------------------------------------------------

    elif (
        innings.target is not None
        and innings.total_runs >= innings.target
    ):
        innings_completed = True
        completion_reason = InningsCompletionReason.TARGET_REACHED

        if hasattr(state, "match"):
            if hasattr(state.match, "winner"):
                state.match.winner = batting_team

            if hasattr(state.match, "status"):
                state.match.status = MatchStatus.COMPLETED

    # --------------------------------------------------------------
    # Declaration (supported if the model exposes it)
    # --------------------------------------------------------------

    elif (
        hasattr(ball_input, "declare_innings")
        and ball_input.declare_innings
    ):
        innings_completed = True

        if hasattr(InningsCompletionReason, "DECLARATION"):
            completion_reason = InningsCompletionReason.DECLARATION
        else:
            completion_reason = "DECLARATION"

    # --------------------------------------------------------------
    # Persist completion state
    # --------------------------------------------------------------

    if hasattr(innings, "completed"):
        innings.completed = innings_completed

    if hasattr(innings, "is_complete"):
        innings.is_complete = innings_completed

    if hasattr(innings, "completion_reason"):
        innings.completion_reason = completion_reason

    if hasattr(state, "innings_complete"):
        state.innings_complete = innings_completed

    if hasattr(state, "match_status"):
        if innings_completed:
            state.match_status = MatchStatus.INNINGS_COMPLETE

    # Chase status
    chase_completed = (
        completion_reason == InningsCompletionReason.TARGET_REACHED
        if innings.target is not None
        else False
    )

    if hasattr(state, "chase_completed"):
        state.chase_completed = chase_completed

    # --------------------------------------------------------------
    # Populate BallResult
    # --------------------------------------------------------------

    result.innings_complete = innings_completed
    result.completion_reason = completion_reason
    result.chase_completed = chase_completed

    if hasattr(result, "match_status"):
        if hasattr(state, "match_status"):
            result.match_status = state.match_status

    if hasattr(result, "winner"):
        if hasattr(state, "match") and hasattr(state.match, "winner"):
            result.winner = state.match.winner






# ============================================================================
# apply_delivery() finalization helpers
# ============================================================================

from copy import deepcopy


def _swap_batters(
    striker: BatterState,
    non_striker: BatterState,
) -> tuple[BatterState, BatterState]:
    """
    Swap striker and non-striker.

    This helper centralizes strike rotation so every caller performs the
    transition consistently.
    """
    return non_striker, striker


def _build_next_innings_state(
    previous: InningsState,
    *,
    innings: Innings,
    batting_team: TeamState,
    bowling_team: TeamState,
    striker: BatterState,
    non_striker: BatterState,
    bowler: BowlerState,
) -> InningsState:
    """
    Construct the next immutable InningsState.

    A new state instance is returned rather than mutating the previous
    instance in-place. This guarantees deterministic state transitions and
    simplifies replay, undo, simulation and testing.
    """
    return replace(
        previous,
        innings=innings,
        batting_team=batting_team,
        bowling_team=bowling_team,
        striker=striker,
        non_striker=non_striker,
        current_bowler=bowler,
    )


# ============================================================================
# apply_delivery() return finalization
#
# Replace the temporary:
#
#     return state, result
#
# with the following block.
# ============================================================================

    # ----------------------------------------------------------------------
    # Synchronize BallResult with the finalized state.
    # ----------------------------------------------------------------------

    result.striker = striker
    result.non_striker = non_striker
    result.bowler = bowler

    result.total_runs = innings.total_runs
    result.total_wickets = innings.wickets
    result.legal_balls = innings.legal_balls

    if hasattr(innings, "current_over"):
        result.current_over = innings.current_over

    if hasattr(innings, "completed"):
        result.innings_complete = innings.completed

    # ----------------------------------------------------------------------
    # Produce the next immutable state.
    # ----------------------------------------------------------------------

    next_state = _build_next_innings_state(
        state,
        innings=innings,
        batting_team=batting_team,
        bowling_team=bowling_team,
        striker=striker,
        non_striker=non_striker,
        bowler=bowler,
    )

    return next_state, result


# ============================================================================
# Public exports
# ============================================================================

for _symbol in (
    "apply_delivery",
    "_swap_batters",
    "_build_next_innings_state",
):
    if _symbol not in __all__:
        __all__.append(_symbol)


# ============================================================================
# WICKET FOUNDATION — ENUMS & CONSTANTS
# ============================================================================

from enum import Enum
from typing import Final, FrozenSet


class DismissalKind(str, Enum):
    """
    Supported dismissal types.

    Values intentionally use ICC terminology while also preserving
    legacy compatibility where required.
    """

    NONE = "NONE"

    # Bowler credited
    BOWLED = "BOWLED"
    CAUGHT = "CAUGHT"
    LBW = "LBW"
    STUMPED = "STUMPED"
    HIT_WICKET = "HIT_WICKET"

    # Not necessarily credited to bowler
    RUN_OUT = "RUN_OUT"
    OBSTRUCTING_THE_FIELD = "OBSTRUCTING_THE_FIELD"
    HIT_BALL_TWICE = "HIT_BALL_TWICE"
    TIMED_OUT = "TIMED_OUT"

    # Retirement
    RETIRED_OUT = "RETIRED_OUT"
    RETIRED_HURT = "RETIRED_HURT"

    # Legacy (Law removed but retained for workbook compatibility)
    HANDLED_BALL = "HANDLED_BALL"


# ----------------------------------------------------------------------------
# Bowler credited wickets
#
# These dismissals increment:
#   • Bowler wickets
#   • Team wickets
#   • Require a replacement batter
# ----------------------------------------------------------------------------

BOWLER_WICKETS: Final[FrozenSet[DismissalKind]] = frozenset(
    {
        DismissalKind.BOWLED,
        DismissalKind.CAUGHT,
        DismissalKind.LBW,
        DismissalKind.STUMPED,
        DismissalKind.HIT_WICKET,
    }
)


# ----------------------------------------------------------------------------
# Team wickets
#
# Every dismissal that legally counts as a wicket in the innings.
# Retired Hurt is intentionally excluded because it is NOT a wicket.
# ----------------------------------------------------------------------------

TEAM_WICKETS: Final[FrozenSet[DismissalKind]] = frozenset(
    {
        DismissalKind.BOWLED,
        DismissalKind.CAUGHT,
        DismissalKind.LBW,
        DismissalKind.RUN_OUT,
        DismissalKind.STUMPED,
        DismissalKind.HIT_WICKET,
        DismissalKind.OBSTRUCTING_THE_FIELD,
        DismissalKind.HIT_BALL_TWICE,
        DismissalKind.TIMED_OUT,
        DismissalKind.RETIRED_OUT,
        DismissalKind.HANDLED_BALL,
    }
)


# ----------------------------------------------------------------------------
# Dismissals requiring the next batter to enter.
#
# Retired Hurt is intentionally excluded because the batter may resume
# later under the Laws of Cricket.
# ----------------------------------------------------------------------------

NEW_BATTER_DISMISSALS: Final[FrozenSet[DismissalKind]] = frozenset(
    {
        DismissalKind.BOWLED,
        DismissalKind.CAUGHT,
        DismissalKind.LBW,
        DismissalKind.RUN_OUT,
        DismissalKind.STUMPED,
        DismissalKind.HIT_WICKET,
        DismissalKind.OBSTRUCTING_THE_FIELD,
        DismissalKind.HIT_BALL_TWICE,
        DismissalKind.TIMED_OUT,
        DismissalKind.RETIRED_OUT,
        DismissalKind.HANDLED_BALL,
    }
)


# ----------------------------------------------------------------------------
# Dismissals where a fielder identity may be recorded.
#
# Although not mandatory for every dismissal, these dismissal types can
# legitimately reference a fielder in official scorecards.
# ----------------------------------------------------------------------------

FIELDER_REQUIRED_DISMISSALS: Final[FrozenSet[DismissalKind]] = frozenset(
    {
        DismissalKind.CAUGHT,
        DismissalKind.RUN_OUT,
        DismissalKind.STUMPED,
        DismissalKind.OBSTRUCTING_THE_FIELD,
    }
)


# ----------------------------------------------------------------------------
# Dismissals that do NOT credit the bowler with a wicket.
# ----------------------------------------------------------------------------

BOWLER_NOT_CREDITED_DISMISSALS: Final[FrozenSet[DismissalKind]] = frozenset(
    {
        DismissalKind.RUN_OUT,
        DismissalKind.OBSTRUCTING_THE_FIELD,
        DismissalKind.HIT_BALL_TWICE,
        DismissalKind.TIMED_OUT,
        DismissalKind.RETIRED_OUT,
        DismissalKind.RETIRED_HURT,
        DismissalKind.HANDLED_BALL,
    }
)


# ============================================================================
# WICKET CLASSIFICATION HELPERS
# ============================================================================

def is_bowler_wicket(dismissal: DismissalKind) -> bool:
    """
    Determine whether the dismissal is credited to the bowler.

    This helper centralizes the classification logic so that callers never
    inspect dismissal types directly.

    Parameters
    ----------
    dismissal:
        The dismissal kind being evaluated.

    Returns
    -------
    bool
        True if the bowler receives a wicket; otherwise False.
    """
    return dismissal in BOWLER_WICKETS


def counts_team_wicket(dismissal: DismissalKind) -> bool:
    """
    Determine whether the dismissal increments the batting side's wicket count.

    Examples
    --------
    Counts:
        - Bowled
        - Caught
        - Run Out
        - Timed Out
        - Retired Out

    Does not count:
        - None
        - Retired Hurt

    Parameters
    ----------
    dismissal:
        The dismissal kind being evaluated.

    Returns
    -------
    bool
        True if the dismissal is recorded as a team wicket.
    """
    return dismissal in TEAM_WICKETS


def requires_new_batter(dismissal: DismissalKind) -> bool:
    """
    Determine whether a replacement batter must enter immediately.

    This helper intentionally distinguishes Retired Hurt from Retired Out.
    Retired Hurt does not consume a wicket and the batter may legally
    resume their innings later.

    Parameters
    ----------
    dismissal:
        The dismissal kind being evaluated.

    Returns
    -------
    bool
        True if a new batter is required before play continues.
    """
    return dismissal in NEW_BATTER_DISMISSALS


def is_fielder_required(dismissal: DismissalKind) -> bool:
    """
    Determine whether the dismissal normally records an associated fielder.

    Examples include:
        - Catcher
        - Wicketkeeper (stumping)
        - Run-out participant
        - Fielder involved in obstructing the field

    The helper answers only whether a fielder identity is applicable,
    not whether one has already been supplied.

    Parameters
    ----------
    dismissal:
        The dismissal kind being evaluated.

    Returns
    -------
    bool
        True if a fielder should be recorded for the dismissal.
    """
    return dismissal in FIELDER_REQUIRED_DISMISSALS


# ============================================================================
# IMMUTABLE WICKET MODELS
# ============================================================================

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True, slots=True)
class DismissalInfo:
    """
    Immutable description of a dismissal.

    This model contains only the factual details describing how a wicket
    occurred. It is intentionally independent of InningsState so it can be
    safely embedded inside BallResult, scorecards, logs, replay data, audit
    trails, and serialization formats.

    Attributes
    ----------
    dismissal_type
        Classification of the dismissal.

    dismissed_batter_id
        Identifier of the dismissed batter. None if no dismissal occurred.

    bowler_id
        Identifier of the bowler involved in the dismissal, when applicable.

    fielder_id
        Identifier of the primary fielder associated with the dismissal.
        For example:
            • Catcher
            • Wicketkeeper (stumping)
            • Run-out participant

    description
        Human-readable dismissal description suitable for scorecards or logs.

    counts_as_team_wicket
        Cached classification indicating whether the dismissal increments the
        batting team's wicket count.

    credited_to_bowler
        Cached classification indicating whether the wicket is credited to the
        bowler.
    """

    dismissal_type: DismissalKind = DismissalKind.NONE
    dismissed_batter_id: Optional[str] = None
    bowler_id: Optional[str] = None
    fielder_id: Optional[str] = None
    description: str = ""
    counts_as_team_wicket: bool = False
    credited_to_bowler: bool = False


@dataclass(frozen=True, slots=True)
class WicketOutcome:
    """
    Immutable result of wicket processing for a single delivery.

    This model captures the state transition decisions made after dismissal
    evaluation while remaining independent of InningsState mutation logic.

    It is intended to be produced by wicket-processing helpers and consumed by
    apply_delivery() when constructing the next immutable InningsState.

    Attributes
    ----------
    dismissal
        Complete dismissal information for the delivery.

    wicket_increment
        Number of wickets to add to the batting side (typically 0 or 1).

    requires_new_batter
        Indicates whether a replacement batter must enter before the next ball.

    innings_complete
        True if the wicket ends the innings (for example, all out).

    next_striker_id
        Batter identifier who should become striker after wicket processing.
        None indicates the caller must determine the value.

    next_non_striker_id
        Batter identifier who should become non-striker after wicket
        processing. None indicates the caller must determine the value.
    """

    dismissal: DismissalInfo
    wicket_increment: int = 0
    requires_new_batter: bool = False
    innings_complete: bool = False
    next_striker_id: Optional[str] = None
    next_non_striker_id: Optional[str] = None



# ============================================================================
# DISMISSAL VALIDATION HELPERS
# ============================================================================

def validate_dismissed_batter(
    dismissal: DismissalKind,
    dismissed_batter_id: str | None,
    state: "InningsState",
) -> None:
    """
    Validate the dismissed batter for a dismissal.

    Rules
    -----
    * No validation is required if no dismissal occurred.
    * Every dismissal that counts as a wicket must identify a batter.
    * The dismissed batter must currently be one of the two batters at the
      wicket (striker or non-striker).

    Parameters
    ----------
    dismissal
        Dismissal classification.

    dismissed_batter_id
        Identifier of the dismissed batter.

    state
        Current immutable innings state.

    Raises
    ------
    ValidationError
        If the dismissed batter information is invalid.
    """
    if dismissal is DismissalKind.NONE:
        return

    if dismissed_batter_id is None:
        raise ValidationError(
            "A dismissed batter must be supplied for a dismissal."
        )

    if dismissed_batter_id not in state.batters:
        raise ValidationError(
            f"Unknown batter: {dismissed_batter_id!r}."
        )

    if dismissed_batter_id not in (
        state.striker_id,
        state.non_striker_id,
    ):
        raise ValidationError(
            "Dismissed batter must currently be batting."
        )


def validate_credited_bowler(
    dismissal: DismissalKind,
    bowler_id: str | None,
    state: "InningsState",
) -> None:
    """
    Validate bowler attribution for a dismissal.

    Rules
    -----
    * Bowler-credit dismissals require a bowler.
    * Non-bowler dismissals must not specify a credited bowler.
    * The supplied bowler must be the current bowler.

    Parameters
    ----------
    dismissal
        Dismissal classification.

    bowler_id
        Credited bowler identifier.

    state
        Current innings state.

    Raises
    ------
    ValidationError
        If bowler attribution is invalid.
    """
    if is_bowler_wicket(dismissal):
        if bowler_id is None:
            raise ValidationError(
                "This dismissal requires a credited bowler."
            )

        if bowler_id != state.current_bowler_id:
            raise ValidationError(
                "Credited bowler must be the current bowler."
            )

        return

    if bowler_id is not None:
        raise ValidationError(
            "This dismissal must not specify a credited bowler."
        )


def validate_credited_fielder(
    dismissal: DismissalKind,
    fielder_id: str | None,
    state: "InningsState",
) -> None:
    """
    Validate fielder attribution for a dismissal.

    Rules
    -----
    * Dismissals requiring a fielder must supply one.
    * Other dismissals must not specify a fielder.
    * The supplied player must exist in the fielding side.

    Parameters
    ----------
    dismissal
        Dismissal classification.

    fielder_id
        Credited fielder identifier.

    state
        Current innings state.

    Raises
    ------
    ValidationError
        If fielder attribution is invalid.
    """
    if is_fielder_required(dismissal):
        if fielder_id is None:
            raise ValidationError(
                "This dismissal requires a credited fielder."
            )

        if fielder_id not in state.bowling_team_players:
            raise ValidationError(
                f"Unknown fielding player: {fielder_id!r}."
            )

        return

    if fielder_id is not None:
        raise ValidationError(
            "This dismissal must not specify a credited fielder."
        )



# ============================================================================
# DISMISSAL BUILDER
# ============================================================================

def build_dismissal_info(
    *,
    dismissal_type: DismissalKind = DismissalKind.NONE,
    state: "InningsState",
    dismissed_batter_id: str | None = None,
    bowler_id: str | None = None,
    fielder_id: str | None = None,
    description: str | None = None,
) -> DismissalInfo:
    """
    Construct a fully validated immutable :class:`DismissalInfo`.

    All dismissal validation is centralized here. The function delegates every
    rule to the existing helper functions so that dismissal classification and
    validation logic remain defined in a single location.

    Parameters
    ----------
    dismissal_type
        Type of dismissal.

    state
        Current innings state.

    dismissed_batter_id
        Batter dismissed by this delivery, if any.

    bowler_id
        Bowler credited with the dismissal when applicable.

    fielder_id
        Fielder involved in the dismissal when applicable.

    description
        Optional scorecard description. If omitted, a sensible default is
        generated.

    Returns
    -------
    DismissalInfo
        A fully validated immutable dismissal description.

    Raises
    ------
    ValidationError
        Propagated from the validation helper functions.
    """

    # ------------------------------------------------------------------
    # Validate supplied identifiers.
    # ------------------------------------------------------------------
    validate_dismissed_batter(
        dismissal=dismissal_type,
        dismissed_batter_id=dismissed_batter_id,
        state=state,
    )

    validate_credited_bowler(
        dismissal=dismissal_type,
        bowler_id=bowler_id,
        state=state,
    )

    validate_credited_fielder(
        dismissal=dismissal_type,
        fielder_id=fielder_id,
        state=state,
    )

    # ------------------------------------------------------------------
    # Derive immutable classification flags.
    # ------------------------------------------------------------------
    counts_as_team_wicket = counts_team_wicket(dismissal_type)
    credited_to_bowler = is_bowler_wicket(dismissal_type)

    # ------------------------------------------------------------------
    # Populate a default description if one was not supplied.
    # ------------------------------------------------------------------
    if description is None:
        if dismissal_type is DismissalKind.NONE:
            description = ""
        else:
            description = dismissal_type.name.replace("_", " ").title()

    return DismissalInfo(
        dismissal_type=dismissal_type,
        dismissed_batter_id=dismissed_batter_id,
        bowler_id=bowler_id,
        fielder_id=fielder_id,
        description=description,
        counts_as_team_wicket=counts_as_team_wicket,
        credited_to_bowler=credited_to_bowler,
    )



# ============================================================================
# WICKET FRAMEWORK — FINAL UTILITIES
# ============================================================================
#
# These helpers intentionally remain independent of apply_delivery().
# They provide a stable API for the dismissal application engine
# implemented in Part 5L.
# ============================================================================

from typing import Final


#: Maximum number of wickets that may fall from a single delivery.
#: (Excludes retired dismissals occurring between deliveries.)
MAX_WICKETS_PER_DELIVERY: Final[int] = 1


def is_dismissal(dismissal: DismissalKind) -> bool:
    """
    Return True if the supplied value represents any dismissal.

    This helper should be preferred over direct comparisons against
    ``DismissalKind.NONE`` to keep dismissal detection centralized.
    """
    return dismissal is not DismissalKind.NONE


def dismissal_requires_validation(dismissal: DismissalKind) -> bool:
    """
    Determine whether dismissal-specific validation should be executed.

    Every dismissal except ``NONE`` requires validation.
    """
    return is_dismissal(dismissal)


def dismissal_description(dismissal: DismissalKind) -> str:
    """
    Return the canonical human-readable description for a dismissal.

    This function provides a single location for generating default
    dismissal text throughout the scoring engine.
    """
    if dismissal is DismissalKind.NONE:
        return ""

    return dismissal.name.replace("_", " ").title()


def dismissal_wicket_increment(dismissal: DismissalKind) -> int:
    """
    Return the number of team wickets contributed by the dismissal.

    Centralizing this calculation ensures future law changes require
    modification in only one location.
    """
    return int(counts_team_wicket(dismissal))


def create_empty_dismissal() -> DismissalInfo:
    """
    Construct an immutable object representing 'no dismissal'.

    This helper avoids repeated construction logic throughout the
    scoring engine.
    """
    return DismissalInfo(
        dismissal_type=DismissalKind.NONE,
        dismissed_batter_id=None,
        bowler_id=None,
        fielder_id=None,
        description="",
        counts_as_team_wicket=False,
        credited_to_bowler=False,
    )


EMPTY_DISMISSAL: Final[DismissalInfo] = create_empty_dismissal()


def create_wicket_outcome(
    dismissal: DismissalInfo = EMPTY_DISMISSAL,
    *,
    innings_complete: bool = False,
    next_striker_id: str | None = None,
    next_non_striker_id: str | None = None,
) -> WicketOutcome:
    """
    Build a validated immutable WicketOutcome.

    All derived values are computed using the shared dismissal helper
    functions to avoid duplicated business rules.
    """
    return WicketOutcome(
        dismissal=dismissal,
        wicket_increment=dismissal_wicket_increment(
            dismissal.dismissal_type
        ),
        requires_new_batter=requires_new_batter(
            dismissal.dismissal_type
        ),
        innings_complete=innings_complete,
        next_striker_id=next_striker_id,
        next_non_striker_id=next_non_striker_id,
    )


EMPTY_WICKET_OUTCOME: Final[WicketOutcome] = create_wicket_outcome()


def is_innings_all_out(
    wickets_after_delivery: int,
    wickets_per_innings: int,
) -> bool:
    """
    Determine whether the innings has ended due to all wickets falling.

    Parameters
    ----------
    wickets_after_delivery
        Team wicket count after processing the current delivery.

    wickets_per_innings
        Maximum wickets permitted in the innings.

    Returns
    -------
    bool
        True if the batting side is all out.
    """
    return wickets_after_delivery >= wickets_per_innings



# ============================================================================
# Part 5L-1 - Shared Wicket Processor Utilities
# ============================================================================

from typing import Optional


def _validate_dismissal_info(
    dismissal: DismissalInfo,
) -> None:
    """
    Validate a DismissalInfo instance before any wicket processor executes.

    This routine intentionally performs only structural validation.
    Dismissal-specific validation belongs inside the individual processors.

    Raises
    ------
    ValueError
        If mandatory dismissal information is missing.
    """
    if dismissal is None:
        raise ValueError("dismissal information is required")

    if dismissal.dismissal_type is None:
        raise ValueError("dismissal type is required")

    if dismissal.dismissed_player_id is None:
        raise ValueError("dismissed player id is required")


def _validate_ballinput_for_wicket(
    ball: BallInput,
) -> None:
    """
    Validate that the supplied BallInput can legally contain
    wicket information.

    This helper deliberately avoids any dismissal-specific logic.
    """
    if ball is None:
        raise ValueError("BallInput cannot be None")

    if ball.dismissal is None:
        raise ValueError("BallInput does not contain dismissal information")


def _validate_dismissed_batter(
    state: InningsState,
    batter_id: str,
) -> None:
    """
    Ensure the dismissed player is one of the two active batters.
    """
    if batter_id not in {
        state.striker_id,
        state.non_striker_id,
    }:
        raise ValueError(
            "dismissed player must be one of the active batters"
        )


def _validate_bowler_identity(
    state: InningsState,
    bowler_id: Optional[str],
) -> None:
    """
    Validate a credited bowler.

    None is permitted because several dismissal types
    (for example Run Out or Retired Out)
    legitimately have no credited bowler.
    """
    if bowler_id is None:
        return

    if bowler_id != state.current_bowler_id:
        raise ValueError(
            "credited bowler must equal current bowler"
        )


def _validate_fielder_identity(
    state: InningsState,
    fielder_id: Optional[str],
) -> None:
    """
    Validate a credited fielder.

    None is allowed for dismissals without a fielder.
    """
    if fielder_id is None:
        return

    batting_team = state.batting_team_id

    if fielder_id in state.team_players.get(batting_team, set()):
        raise ValueError(
            "fielder cannot belong to batting side"
        )


def _determine_wicket_increment(
    dismissal: DismissalInfo,
) -> int:
    """
    Determine how many wickets should be added.

    Current Laws of Cricket award exactly one wicket
    for every supported dismissal handled by this engine.
    """
    return 1


def _determine_delivery_legality(
    ball: BallInput,
) -> bool:
    """
    Determine whether the delivery counts as legal.

    Reuses the shared legality helper created in Part 5K.
    """
    return _is_legal_delivery(ball)


def _dismissal_description(
    dismissal_type: DismissalType,
    batter_name: str,
    bowler_name: Optional[str] = None,
    fielder_name: Optional[str] = None,
) -> str:
    """
    Produce the human-readable dismissal description used by
    scorecards and commentary.

    This helper contains presentation logic only.
    """

    if dismissal_type == DismissalType.BOWLED:
        return f"{batter_name} b {bowler_name}"

    if dismissal_type == DismissalType.CAUGHT:
        return f"{batter_name} c {fielder_name} b {bowler_name}"

    if dismissal_type == DismissalType.CAUGHT_AND_BOWLED:
        return f"{batter_name} c & b {bowler_name}"

    if dismissal_type == DismissalType.LBW:
        return f"{batter_name} lbw b {bowler_name}"

    if dismissal_type == DismissalType.RUN_OUT:
        if fielder_name:
            return f"{batter_name} run out ({fielder_name})"
        return f"{batter_name} run out"

    if dismissal_type == DismissalType.STUMPED:
        return f"{batter_name} st {fielder_name} b {bowler_name}"

    if dismissal_type == DismissalType.HIT_WICKET:
        return f"{batter_name} hit wicket b {bowler_name}"

    if dismissal_type == DismissalType.RETIRED_OUT:
        return f"{batter_name} retired out"

    return f"{batter_name} out"


def _build_wicket_outcome(
    *,
    dismissal_type: DismissalType,
    dismissed_player_id: str,
    credited_bowler_id: Optional[str],
    credited_fielder_id: Optional[str],
    description: str,
    legal_delivery: bool,
    wicket_increment: int,
    new_batter_required: bool = True,
) -> WicketOutcome:
    """
    Construct an immutable WicketOutcome.

    This helper centralizes construction so every processor
    produces a consistent object.
    """
    return WicketOutcome(
        dismissal_type=dismissal_type,
        dismissed_player_id=dismissed_player_id,
        credited_bowler_id=credited_bowler_id,
        credited_fielder_id=credited_fielder_id,
        description=description,
        wicket_increment=wicket_increment,
        legal_delivery=legal_delivery,
        new_batter_required=new_batter_required,
    )


# ============================================================================
# Part 5L-2 - Bowled / LBW / Hit Wicket Processors
# ============================================================================


def _process_bowled(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Bowled dismissal.

    A bowled dismissal always:

    * credits the current bowler
    * has no credited fielder
    * requires a new batter
    * increments the wicket count by one

    This function performs validation only and returns an immutable
    WicketOutcome. It does not modify the innings state.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.BOWLED:
        raise ValueError("expected Bowled dismissal")

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler = state.current_bowler_id

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    description = _dismissal_description(
        dismissal_type=DismissalType.BOWLED,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.BOWLED,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=None,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


def _process_lbw(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process an LBW dismissal.

    An LBW dismissal always:

    * credits the current bowler
    * has no credited fielder
    * requires a new batter
    * increments the wicket count by one

    The function is pure and performs no innings mutation.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.LBW:
        raise ValueError("expected LBW dismissal")

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler = state.current_bowler_id

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    description = _dismissal_description(
        dismissal_type=DismissalType.LBW,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.LBW,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=None,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


def _process_hit_wicket(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Hit Wicket dismissal.

    A hit wicket dismissal:

    * credits the current bowler
    * has no credited fielder
    * requires a replacement batter
    * increments the wicket tally by one

    The processor is completely pure and returns only the generated
    WicketOutcome.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.HIT_WICKET:
        raise ValueError("expected Hit Wicket dismissal")

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler = state.current_bowler_id

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    description = _dismissal_description(
        dismissal_type=DismissalType.HIT_WICKET,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.HIT_WICKET,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=None,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


# ============================================================================
# Part 5L-3 - Caught Dismissal Processors
# ============================================================================


def _process_caught(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Caught dismissal.

    A standard caught dismissal:

    * credits the current bowler
    * credits the catching fielder
    * requires a replacement batter
    * increments the wicket count by one

    This function is pure and performs no mutation of the innings state.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.CAUGHT:
        raise ValueError("expected Caught dismissal")

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler = state.current_bowler_id
    credited_fielder = dismissal.fielder_id

    if credited_fielder is None:
        raise ValueError(
            "caught dismissal requires a credited fielder"
        )

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    _validate_fielder_identity(
        state,
        credited_fielder,
    )

    description = _dismissal_description(
        dismissal_type=DismissalType.CAUGHT,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
        fielder_name=dismissal.fielder_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.CAUGHT,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=credited_fielder,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


def _process_caught_and_bowled(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Caught and Bowled dismissal.

    In this dismissal the bowler is also the catcher. The same player
    therefore receives both bowling and fielding credit.

    Characteristics:

    * credited bowler = current bowler
    * credited fielder = current bowler
    * new batter required
    * wicket increment = one

    The function is completely pure and returns an immutable
    WicketOutcome.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.CAUGHT_AND_BOWLED:
        raise ValueError(
            "expected Caught and Bowled dismissal"
        )

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler = state.current_bowler_id
    credited_fielder = state.current_bowler_id

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    _validate_fielder_identity(
        state,
        credited_fielder,
    )

    description = _dismissal_description(
        dismissal_type=DismissalType.CAUGHT_AND_BOWLED,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
        fielder_name=state.current_bowler_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.CAUGHT_AND_BOWLED,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=credited_fielder,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


# ============================================================================
# Part 5L-4 - Run Out & Stumped Processors
# ============================================================================


def _process_run_out(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Run Out dismissal.

    A run out differs from most dismissal types because:

    * either the striker or non-striker may be dismissed;
    * no bowler is credited with the wicket;
    * a fielder may (or may not) receive fielding credit;
    * the dismissal may occur from either a legal or illegal delivery;
    * a replacement batter is always required.

    This function is completely pure and never mutates the innings state.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.RUN_OUT:
        raise ValueError("expected Run Out dismissal")

    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler: Optional[str] = None
    credited_fielder = dismissal.fielder_id

    if credited_fielder is not None:
        _validate_fielder_identity(
            state,
            credited_fielder,
        )

    description = _dismissal_description(
        dismissal_type=DismissalType.RUN_OUT,
        batter_name=dismissal.dismissed_player_name,
        fielder_name=dismissal.fielder_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.RUN_OUT,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=credited_fielder,
        description=description,
        legal_delivery=_determine_delivery_legality(ball),
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


def _process_stumped(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Stumped dismissal.

    Characteristics:

    * only the striker may be dismissed;
    * the current bowler receives bowling credit;
    * the wicketkeeper receives fielding credit;
    * the dismissal is valid only from a legal delivery;
    * a replacement batter is required.

    The processor performs validation and returns an immutable
    WicketOutcome without modifying the supplied InningsState.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.STUMPED:
        raise ValueError("expected Stumped dismissal")

    if dismissal.dismissed_player_id != state.striker_id:
        raise ValueError(
            "only the striker may be stumped"
        )

    credited_bowler = state.current_bowler_id
    credited_fielder = dismissal.fielder_id

    if credited_fielder is None:
        raise ValueError(
            "stumped dismissal requires a credited fielder"
        )

    _validate_bowler_identity(
        state,
        credited_bowler,
    )

    _validate_fielder_identity(
        state,
        credited_fielder,
    )

    legal_delivery = _determine_delivery_legality(ball)

    if not legal_delivery:
        raise ValueError(
            "stumped dismissal requires a legal delivery"
        )

    description = _dismissal_description(
        dismissal_type=DismissalType.STUMPED,
        batter_name=dismissal.dismissed_player_name,
        bowler_name=state.current_bowler_name,
        fielder_name=dismissal.fielder_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.STUMPED,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=credited_fielder,
        description=description,
        legal_delivery=legal_delivery,
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )


# ============================================================================
# Part 5L-5 - Retired Out Processor
# ============================================================================


def _process_retired_out(
    state: InningsState,
    ball: BallInput,
) -> WicketOutcome:
    """
    Process a Retired Out dismissal.

    A Retired Out dismissal is fundamentally different from all other
    dismissals because it is not caused by a delivery.

    Characteristics
    ---------------
    * Either active batter may retire out.
    * No bowler is credited.
    * No fielder is credited.
    * Counts as one team wicket.
    * No legal delivery is involved.
    * A replacement batter is always required.

    This processor is completely pure. It validates the supplied inputs,
    constructs an immutable WicketOutcome and performs no mutation of the
    supplied InningsState.
    """
    _validate_ballinput_for_wicket(ball)

    dismissal = ball.dismissal
    _validate_dismissal_info(dismissal)

    if dismissal.dismissal_type != DismissalType.RETIRED_OUT:
        raise ValueError("expected Retired Out dismissal")

    # The retiring batter must be one of the two currently active batters.
    _validate_dismissed_batter(
        state,
        dismissal.dismissed_player_id,
    )

    credited_bowler: Optional[str] = None
    credited_fielder: Optional[str] = None

    description = _dismissal_description(
        dismissal_type=DismissalType.RETIRED_OUT,
        batter_name=dismissal.dismissed_player_name,
    )

    return _build_wicket_outcome(
        dismissal_type=DismissalType.RETIRED_OUT,
        dismissed_player_id=dismissal.dismissed_player_id,
        credited_bowler_id=credited_bowler,
        credited_fielder_id=credited_fielder,
        description=description,
        # Retired Out has no delivery associated with it.
        legal_delivery=False,
        wicket_increment=_determine_wicket_increment(dismissal),
        new_batter_required=True,
    )

# ============================================================================
# Part 5L-6 — Wicket Processor Registry
# ============================================================================

from types import MappingProxyType
from typing import Callable, Final

#: Type alias for wicket processor functions.
WicketProcessor = Callable[
    [InningsState, BallInput],
    WicketOutcome,
]


#: Immutable registry mapping dismissal types to their processors.
_WICKET_PROCESSOR_REGISTRY: Final[
    Mapping[DismissalType, WicketProcessor]
] = MappingProxyType(
    {
        DismissalType.BOWLED: _process_bowled,
        DismissalType.CAUGHT: _process_caught,
        DismissalType.CAUGHT_AND_BOWLED: _process_caught_and_bowled,
        DismissalType.LBW: _process_lbw,
        DismissalType.RUN_OUT: _process_run_out,
        DismissalType.STUMPED: _process_stumped,
        DismissalType.HIT_WICKET: _process_hit_wicket,
        DismissalType.RETIRED_OUT: _process_retired_out,
    }
)


def get_wicket_processor(
    dismissal_type: DismissalType,
) -> WicketProcessor:
    """
    Return the registered processor for a dismissal type.

    Parameters
    ----------
    dismissal_type:
        Type of dismissal being processed.

    Returns
    -------
    WicketProcessor
        Callable responsible for producing the corresponding
        ``WicketOutcome``.

    Raises
    ------
    ValidationError
        If the dismissal type is unsupported or has no registered
        processor.
    """
    processor = _WICKET_PROCESSOR_REGISTRY.get(dismissal_type)
    if processor is None:
        raise ValidationError(
            f"Unsupported dismissal type: {dismissal_type!r}"
        )
    return processor


# ============================================================================
# Part 5L-7 — Wicket Processor Framework Finalization
# ============================================================================

from typing import Final, Iterable


#: Public export surface for the wicket-processing subsystem.
__all__: Final[tuple[str, ...]] = (
    "WicketProcessor",
    "get_wicket_processor",
)


def is_supported_dismissal(
    dismissal_type: DismissalType,
) -> bool:
    """
    Return whether a dismissal type has a registered processor.

    This helper performs no validation and is intended for callers that
    need a lightweight capability check before dispatch.
    """
    return dismissal_type in _WICKET_PROCESSOR_REGISTRY


def iter_supported_dismissals() -> tuple[DismissalType, ...]:
    """
    Return all supported dismissal types.

    A tuple is returned to preserve immutability while providing a stable
    iteration order for diagnostics, validation, and future integration.
    """
    return tuple(_WICKET_PROCESSOR_REGISTRY.keys())


def iter_wicket_processors() -> tuple[WicketProcessor, ...]:
    """
    Return all registered wicket processors.

    The returned tuple is immutable and may be used for inspection,
    testing, or framework initialization without exposing the underlying
    registry.
    """
    return tuple(_WICKET_PROCESSOR_REGISTRY.values())


def validate_dismissal_processor(
    dismissal_type: DismissalType,
) -> None:
    """
    Validate that a processor exists for the supplied dismissal type.

    This centralizes registry validation so later integration code
    (Part 5M) does not duplicate dispatch checks.
    """
    get_wicket_processor(dismissal_type)


def dispatch_wicket_processor(
    dismissal_info: DismissalInfo,
) -> WicketProcessor:
    """
    Resolve the processor for a dismissal.

    This helper intentionally performs only processor resolution.
    It does not invoke the processor, mutate state, or inspect any
    additional match information, keeping the processor framework pure
    and preparing a single dispatch entry point for Part 5M.
    """
    return get_wicket_processor(dismissal_info.dismissal_type)



