"""
validation.py
=============

Reusable Excel Validation Utilities
===================================

This module provides a workbook-independent abstraction for creating and
managing validation rules used throughout the Cricket Tournament Manager.

The primary objective is to keep *validation definitions* separate from
*worksheet layout*. A validation should describe **what is allowed**, while
modules such as ``workbook.py`` decide **where** that validation is applied.

Why this module exists
----------------------

Excel's Data Validation system is powerful but verbose. Creating validation
objects repeatedly throughout the codebase leads to:

    • duplicated logic
    • inconsistent prompts
    • inconsistent error messages
    • workbook-specific implementations
    • difficult testing
    • difficult migration to future platforms

Instead, this module acts as a centralized factory for validation rules.

Design Goals
------------

This module is designed around several long-term principles.

1. Workbook Independence
~~~~~~~~~~~~~~~~~~~~~~~~
This module must never depend on worksheet names, workbook layouts,
table names, or cell coordinates hardcoded elsewhere.

2. Deterministic Behaviour
~~~~~~~~~~~~~~~~~~~~~~~~~~
Every function should return the same result given the same inputs.

No hidden state.

No global workbook references.

No side effects.

3. Future Web Compatibility
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Although the initial implementation targets Microsoft Excel through
openpyxl, the validation definitions themselves should remain generic.

Future implementations should be able to translate these validation
definitions into:

    • HTML forms
    • REST API validation
    • React forms
    • Android forms
    • iOS forms
    • desktop applications

without rewriting business rules.

4. Reusability
~~~~~~~~~~~~~~
All validation builders should be generic enough that they can be reused
outside of cricket scoring.

Example:

Instead of:

    create_team_dropdown()

prefer:

    list_validation(...)

with higher-level cricket-specific wrappers implemented separately.

5. Explicit Configuration
~~~~~~~~~~~~~~~~~~~~~~~~~
Every validation should be configured explicitly.

Hidden defaults should be avoided wherever possible.

6. Testability
~~~~~~~~~~~~~~
This module should be easy to unit test without constructing an Excel
workbook.

Relationship to Other Modules
-----------------------------

formulas.py
    Provides deterministic mathematical calculations.

validation.py
    Creates reusable validation definitions.

workbook.py
    Applies validation rules to workbook cells.

create_match.py
    Uses validation builders when generating score sheets.

score_ball.py
    Relies on workbook validations to ensure legal user input.

Architecture Overview
---------------------

This module will eventually contain several layers.

Layer 1
    Internal helper utilities.

Layer 2
    Generic validation builders.

Layer 3
    Dropdown builders.

Layer 4
    Cricket-specific validation factories.

Layer 5
    Workbook integration helpers.

Only Layers 4 and 5 should know anything about cricket terminology.

Version
-------
Initial development version.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Final
from typing import Iterable
from typing import Optional
from typing import Sequence
from typing import TypeAlias
from typing import Union

from openpyxl.worksheet.datavalidation import DataValidation

###############################################################################
# Type Aliases
###############################################################################

#: Acceptable numeric types used throughout validation builders.
Number: TypeAlias = Union[int, float]

#: Value accepted by Excel validation formulas.
FormulaValue: TypeAlias = Union[str, Number]

#: Collection of string values used for dropdowns.
StringCollection: TypeAlias = Sequence[str]

#: Generic iterable of values.
ValueIterable: TypeAlias = Iterable[FormulaValue]

#: Optional formula parameter.
OptionalFormula: TypeAlias = Optional[FormulaValue]

###############################################################################
# Module Constants
###############################################################################

#: Default Excel prompt title shown when a validated cell is selected.
#
# Centralising this string ensures a consistent user experience across
# every worksheet generated by the application.
DEFAULT_PROMPT_TITLE: Final[str] = "Input Required"

#: Default prompt message.
#
# Individual validators may override this with more specific guidance.
DEFAULT_PROMPT_MESSAGE: Final[str] = (
    "Please enter a valid value."
)

#: Default error title displayed when validation fails.
#
# Using a consistent title makes workbook behaviour predictable.
DEFAULT_ERROR_TITLE: Final[str] = "Invalid Input"

#: Default error message displayed when invalid data is entered.
DEFAULT_ERROR_MESSAGE: Final[str] = (
    "The value entered does not satisfy the validation rules."
)

#: Whether blank cells should be accepted by default.
#
# Blank values are often required while a match is in progress.
DEFAULT_ALLOW_BLANK: Final[bool] = True

#: Whether Excel should display the input prompt.
DEFAULT_SHOW_INPUT_MESSAGE: Final[bool] = True

#: Whether Excel should display an error alert.
DEFAULT_SHOW_ERROR_MESSAGE: Final[bool] = True

#: Maximum number of characters supported by an explicit Excel list.
#
# Longer lists require worksheet ranges or named ranges.
EXCEL_INLINE_LIST_LIMIT: Final[int] = 255

#: Maximum worksheet name length supported by Excel.
EXCEL_MAX_SHEET_NAME_LENGTH: Final[int] = 31

#: Maximum cell text length supported by Excel.
EXCEL_MAX_CELL_TEXT_LENGTH: Final[int] = 32767


###############################################################################
# Cricket Validation Value Sets
#
# These immutable tuples serve as the canonical source of truth for all
# cricket-specific dropdown values used throughout the workbook.
#
# Benefits
# --------
# • Single source of truth
# • No duplicated strings
# • Easier maintenance
# • Easier localisation
# • Easier tournament customisation
###############################################################################

YES_NO_OPTIONS: Final[tuple[str, ...]] = (
    "Yes",
    "No",
)

TOSS_DECISIONS: Final[tuple[str, ...]] = (
    "Bat",
    "Bowl",
)

MATCH_RESULTS: Final[tuple[str, ...]] = (
    "Team Won",
    "Tie",
    "No Result",
    "Abandoned",
)

DISMISSAL_TYPES: Final[tuple[str, ...]] = (
    "Bowled",
    "Caught",
    "LBW",
    "Run Out",
    "Stumped",
    "Hit Wicket",
    "Obstructing the Field",
    "Timed Out",
    "Hit the Ball Twice",
    "Retired Out",
    "Retired Hurt",
)

EXTRA_TYPES: Final[tuple[str, ...]] = (
    "None",
    "Bye",
    "Leg Bye",
    "Wide",
    "No Ball",
    "Penalty",
)

BALL_OUTCOMES: Final[tuple[str, ...]] = (
    "Dot Ball",
    "Runs",
    "Boundary Four",
    "Six",
    "Wicket",
    "Wide",
    "No Ball",
    "Bye",
    "Leg Bye",
    "Penalty",
)

DRS_RESULTS: Final[tuple[str, ...]] = (
    "Not Reviewed",
    "Upheld",
    "Overturned",
    "Umpire's Call",
)

BATTING_STYLES: Final[tuple[str, ...]] = (
    "Right-hand Bat",
    "Left-hand Bat",
)

BOWLING_STYLES: Final[tuple[str, ...]] = (
    "Right-arm Fast",
    "Right-arm Fast Medium",
    "Right-arm Medium Fast",
    "Right-arm Medium",
    "Right-arm Off Break",
    "Right-arm Leg Break",
    "Right-arm Leg Spin",
    "Right-arm Googly",
    "Left-arm Fast",
    "Left-arm Fast Medium",
    "Left-arm Medium Fast",
    "Left-arm Medium",
    "Left-arm Orthodox",
    "Left-arm Wrist Spin",
)

POWERPLAY_OPTIONS: Final[tuple[str, ...]] = (
    "None",
    "Mandatory",
    "Batting",
    "Bowling",
)

NO_BALL_REASONS: Final[tuple[str, ...]] = (
    "Front Foot",
    "Back Foot",
    "Above Waist Full Toss",
    "Dangerous Short Ball",
    "Throwing",
    "Multiple Bounce",
    "Breaking Wicket",
    "Fielder Position",
    "Keeper Position",
    "Other",
)

WIDE_REASONS: Final[tuple[str, ...]] = (
    "Off Side",
    "Leg Side",
    "Above Head",
    "Passed Batter",
    "Other",
)

###############################################################################
# Default Configuration
###############################################################################


@dataclass(frozen=True, slots=True)
class ValidationDefaults:
    """
    Immutable default configuration shared by validation builders.

    This dataclass intentionally contains only generic configuration
    independent of any workbook structure.

    Individual validation factory functions may override any value.
    """

    allow_blank: bool = DEFAULT_ALLOW_BLANK
    show_input_message: bool = DEFAULT_SHOW_INPUT_MESSAGE
    show_error_message: bool = DEFAULT_SHOW_ERROR_MESSAGE

    prompt_title: str = DEFAULT_PROMPT_TITLE
    prompt_message: str = DEFAULT_PROMPT_MESSAGE

    error_title: str = DEFAULT_ERROR_TITLE
    error_message: str = DEFAULT_ERROR_MESSAGE

###############################################################################
# Validation Source Abstractions
###############################################################################

from dataclasses import dataclass
from enum import Enum
from typing import Optional


class ValidationSourceType(str, Enum):
    """
    Identifies the source of values used by a dropdown validation.

    This abstraction deliberately separates *where* values originate from
    from *how* an Excel DataValidation object is ultimately created.

    Future workbook implementations may introduce additional source types
    (for example structured table references or spilled arrays) without
    requiring changes to the public validation API.
    """

    #: Explicit inline Excel list.
    EXPLICIT_LIST = "explicit_list"

    #: Worksheet cell range.
    WORKSHEET_RANGE = "worksheet_range"

    #: Workbook defined name.
    NAMED_RANGE = "named_range"

    #: Workbook defined dynamic name.
    DYNAMIC_NAMED_RANGE = "dynamic_named_range"

    #: INDIRECT-based dependent dropdown.
    DEPENDENT = "dependent"

    #: Arbitrary Excel formula.
    FORMULA = "formula"


@dataclass(frozen=True, slots=True)
class ValidationSource:
    """
    Describes where dropdown values originate.

    This class contains no workbook state.

    It simply encapsulates the information needed to build the
    appropriate Excel validation formula.

    Examples
    --------

    Explicit list::

        ValidationSource(
            source_type=ValidationSourceType.EXPLICIT_LIST,
            values=["Yes", "No"]
        )

    Worksheet range::

        ValidationSource(
            source_type=ValidationSourceType.WORKSHEET_RANGE,
            worksheet="Lookup",
            cell_range="A2:A20"
        )

    Named range::

        ValidationSource(
            source_type=ValidationSourceType.NAMED_RANGE,
            name="Teams"
        )

    Dynamic named range::

        ValidationSource(
            source_type=ValidationSourceType.DYNAMIC_NAMED_RANGE,
            name="Players"
        )

    Dependent dropdown::

        ValidationSource(
            source_type=ValidationSourceType.DEPENDENT,
            parent_cell="$A$2"
        )

    Formula::

        ValidationSource(
            source_type=ValidationSourceType.FORMULA,
            formula="OFFSET(...)"
        )
    """

    source_type: ValidationSourceType

    values: Optional[StringCollection] = None

    worksheet: Optional[str] = None

    cell_range: Optional[str] = None

    name: Optional[str] = None

    parent_cell: Optional[str] = None

    formula: Optional[str] = None
###############################################################################
# Validation Types
###############################################################################


class ValidationType(str, Enum):
    """
    Supported Excel validation categories.

    These names intentionally mirror Excel terminology wherever practical,
    making future translation to other platforms straightforward.
    """

    #: Whole number validation.
    WHOLE = "whole"

    #: Decimal number validation.
    DECIMAL = "decimal"

    #: Explicit list or dropdown validation.
    LIST = "list"

    #: Date validation.
    DATE = "date"

    #: Time validation.
    TIME = "time"

    #: Text length validation.
    TEXT_LENGTH = "textLength"

    #: Arbitrary Excel formula validation.
    CUSTOM = "custom"

    #: Accept any value.
    #
    # Mostly useful when dynamically enabling/disabling validation.
    ANY = "any"


###############################################################################
# Comparison Operators
###############################################################################


class Operator(str, Enum):
    """
    Excel comparison operators.

    These operators are reused by multiple validation types including
    numeric, date, time and text-length validations.
    """

    BETWEEN = "between"
    NOT_BETWEEN = "notBetween"

    EQUAL = "equal"
    NOT_EQUAL = "notEqual"

    GREATER_THAN = "greaterThan"
    GREATER_THAN_OR_EQUAL = "greaterThanOrEqual"

    LESS_THAN = "lessThan"
    LESS_THAN_OR_EQUAL = "lessThanOrEqual"


###############################################################################
# Excel Error Styles
###############################################################################


class ErrorStyle(str, Enum):
    """
    Excel validation error styles.

    STOP
        Reject invalid input completely.

    WARNING
        Warn the user but permit override.

    INFORMATION
        Display informational message only.
    """

    STOP = "stop"
    WARNING = "warning"
    INFORMATION = "information"


###############################################################################
# Public API
###############################################################################

__all__ = [
    # Type aliases
    "Number",
    "FormulaValue",
    "StringCollection",
    "ValueIterable",
    "OptionalFormula",
    # Constants
    "DEFAULT_PROMPT_TITLE",
    "DEFAULT_PROMPT_MESSAGE",
    "DEFAULT_ERROR_TITLE",
    "DEFAULT_ERROR_MESSAGE",
    "DEFAULT_ALLOW_BLANK",
    "DEFAULT_SHOW_INPUT_MESSAGE",
    "DEFAULT_SHOW_ERROR_MESSAGE",
    "EXCEL_INLINE_LIST_LIMIT",
    "EXCEL_MAX_SHEET_NAME_LENGTH",
    "EXCEL_MAX_CELL_TEXT_LENGTH",
    # Dataclasses
    "ValidationDefaults",
    "ValidationSourceType",
    "ValidationSource",
    # Enums
    "ValidationType",
    "Operator",
    "ErrorStyle",
    # Future public builders
    "integer_validation",
    "decimal_validation",
    "whole_number_validation",
    "text_length_validation",
    "date_validation",
    "time_validation",
    "custom_formula_validation",
    "list_validation",
    "named_range_validation",
    "worksheet_range_validation",
    "dependent_dropdown_validation",
    "apply_validation",
    "apply_to_cells",
    "apply_to_range",
    "create_named_range",
]


###############################################################################
# Internal Helper Functions
###############################################################################

from collections.abc import Iterable
from openpyxl.utils import get_column_letter
from openpyxl.utils.cell import (
    absolute_coordinate,
    coordinate_from_string,
    range_boundaries,
)


def _quote_sheet_name(sheet_name: str) -> str:
    """
    Return a worksheet name safely quoted for use inside Excel formulas.

    Excel requires worksheet names containing spaces or special characters
    to be enclosed in single quotes.

    Any embedded single quote characters are escaped by doubling them.

    Examples
    --------
    >>> _quote_sheet_name("Scorecard")
    'Scorecard'

    >>> _quote_sheet_name("Team A")
    "'Team A'"

    >>> _quote_sheet_name("Bob's Team")
    "'Bob''s Team'"

    Parameters
    ----------
    sheet_name:
        Worksheet name.

    Returns
    -------
    str
        Properly quoted worksheet name suitable for Excel formulas.

    Raises
    ------
    TypeError
        If sheet_name is not a string.

    ValueError
        If sheet_name is empty.
    """
    _validate_non_empty(sheet_name, "sheet_name")

    escaped = sheet_name.replace("'", "''")

    requires_quotes = any(
        (
            ch.isspace()
            or ch in "[]:*?/\\-+&(){}.,"
            for ch in escaped
        )
    )

    if requires_quotes:
        return f"'{escaped}'"

    return escaped


def _absolute_cell(cell_reference: str) -> str:
    """
    Convert a cell reference into an absolute Excel reference.

    Examples
    --------
    >>> _absolute_cell("A1")
    '$A$1'

    >>> _absolute_cell("c15")
    '$C$15'

    Parameters
    ----------
    cell_reference:
        Excel cell reference.

    Returns
    -------
    str
        Absolute cell reference.

    Raises
    ------
    TypeError
        If the reference is not a string.

    ValueError
        If the reference is invalid.
    """
    _validate_non_empty(cell_reference, "cell_reference")

    try:
        coordinate_from_string(cell_reference.upper())
    except ValueError as exc:
        raise ValueError(
            f"Invalid cell reference: {cell_reference}"
        ) from exc

    return absolute_coordinate(cell_reference.upper())


def _absolute_range(range_reference: str) -> str:
    """
    Convert an Excel range into an absolute range.

    Examples
    --------
    >>> _absolute_range("A1:C5")
    '$A$1:$C$5'

    Parameters
    ----------
    range_reference:
        Excel range.

    Returns
    -------
    str
        Absolute Excel range.

    Raises
    ------
    ValueError
        If the range is invalid.
    """
    _validate_non_empty(range_reference, "range_reference")

    try:
        min_col, min_row, max_col, max_row = range_boundaries(
            range_reference
        )
    except ValueError as exc:
        raise ValueError(
            f"Invalid Excel range: {range_reference}"
        ) from exc

    return (
        f"${get_column_letter(min_col)}${min_row}:"
        f"${get_column_letter(max_col)}${max_row}"
    )


def _column_letter(column: int) -> str:
    """
    Convert a 1-based column number into its Excel letter.

    Examples
    --------
    >>> _column_letter(1)
    'A'

    >>> _column_letter(27)
    'AA'

    Parameters
    ----------
    column:
        One-based column index.

    Returns
    -------
    str
        Excel column letters.

    Raises
    ------
    ValueError
        If the column index is less than one.
    """
    if not isinstance(column, int):
        raise TypeError("column must be an integer")

    if column < 1:
        raise ValueError("column must be >= 1")

    return get_column_letter(column)


def _excel_list(values: StringCollection) -> str:
    """
    Convert an iterable of strings into an Excel inline list.

    Excel stores explicit dropdown lists as a comma-separated string.

    Examples
    --------
    >>> _excel_list(["Yes", "No"])
    '"Yes,No"'

    Parameters
    ----------
    values:
        Sequence of values.

    Returns
    -------
    str
        Excel list formula.

    Raises
    ------
    ValueError
        If the resulting string exceeds Excel's inline limit.
    """
    _validate_iterable(values, "values")

    items = [str(v).strip() for v in values]

    if not items:
        raise ValueError("values cannot be empty")

    joined = ",".join(items)

    if len(joined) > EXCEL_INLINE_LIST_LIMIT:
        raise ValueError(
            "Explicit Excel lists cannot exceed "
            f"{EXCEL_INLINE_LIST_LIMIT} characters."
        )

    return f'"{joined}"'


def _escape_formula(formula: str) -> str:
    """
    Normalise an Excel formula.

    Removes leading '=' if present and trims whitespace.

    Parameters
    ----------
    formula:
        Excel formula.

    Returns
    -------
    str
        Clean formula.
    """
    _validate_non_empty(formula, "formula")

    formula = formula.strip()

    if formula.startswith("="):
        formula = formula[1:]

    return formula


def _validate_non_empty(value: str, name: str) -> None:
    """
    Validate that a string is non-empty.

    Parameters
    ----------
    value:
        String value.

    name:
        Parameter name used in exception messages.

    Raises
    ------
    TypeError
        If value is not a string.

    ValueError
        If value is empty or whitespace.
    """
    if not isinstance(value, str):
        raise TypeError(f"{name} must be a string")

    if not value.strip():
        raise ValueError(f"{name} cannot be empty")


def _validate_iterable(values: Iterable, name: str) -> None:
    """
    Validate an iterable.

    Strings are explicitly rejected because they are iterable but almost
    never represent a collection of dropdown values.

    Parameters
    ----------
    values:
        Iterable object.

    name:
        Parameter name.

    Raises
    ------
    TypeError
        If values is not an iterable collection.
    """
    if isinstance(values, (str, bytes)):
        raise TypeError(
            f"{name} must be an iterable collection, not a string"
        )

    if not isinstance(values, Iterable):
        raise TypeError(f"{name} must be iterable")


def _build_formula_reference(
    sheet_name: str,
    cell_range: str,
) -> str:
    """
    Build a fully-qualified worksheet range reference.

    Examples
    --------
    >>> _build_formula_reference("Teams", "A2:A20")
    "Teams!$A$2:$A$20"

    >>> _build_formula_reference("Team List", "B2:B15")
    "'Team List'!$B$2:$B$15"

    Parameters
    ----------
    sheet_name:
        Worksheet name.

    cell_range:
        Excel range.

    Returns
    -------
    str
        Excel formula reference.
    """
    quoted = _quote_sheet_name(sheet_name)
    absolute = _absolute_range(cell_range)

    return f"{quoted}!{absolute}"


def _is_named_range(reference: str) -> bool:
    """
    Determine whether a string appears to be an Excel named range.

    This performs a lightweight syntactic check only.

    It does **not** verify existence within a workbook.

    Examples
    --------
    >>> _is_named_range("Teams")
    True

    >>> _is_named_range("A1:B10")
    False

    >>> _is_named_range("Sheet1!A1")
    False
    """
    if not isinstance(reference, str):
        return False

    reference = reference.strip()

    if not reference:
        return False

    try:
        range_boundaries(reference)
        return False
    except Exception:
        pass

    if "!" in reference:
        return False

    invalid = set(" :,$[](){}+-*/\\=")

    return not any(ch in invalid for ch in reference)


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "_quote_sheet_name",
        "_absolute_cell",
        "_absolute_range",
        "_column_letter",
        "_excel_list",
        "_escape_formula",
        "_validate_non_empty",
        "_validate_iterable",
        "_build_formula_reference",
        "_is_named_range",
    ]
)

###############################################################################
# Generic Validation Builders (Part 3A)
###############################################################################

from typing import Any


def _build_validation(
    *,
    validation_type: ValidationType,
    operator: Operator | None = None,
    formula1: FormulaValue | None = None,
    formula2: FormulaValue | None = None,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Construct and configure an ``openpyxl`` DataValidation object.

    This helper centralises all DataValidation construction used throughout
    the module. Every public validation builder should delegate object
    creation to this function to ensure deterministic behaviour and
    consistent configuration.

    Parameters
    ----------
    validation_type:
        Excel validation category.

    operator:
        Optional comparison operator.

    formula1:
        Primary comparison formula.

    formula2:
        Secondary comparison formula.

    allow_blank:
        Whether blank cells are permitted.

    prompt_title:
        Input message title.

    prompt_message:
        Input message displayed when the cell is selected.

    error_title:
        Error dialog title.

    error_message:
        Error dialog text.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Fully configured validation object.

    Notes
    -----
    This function intentionally does not attach the validation to any cells.
    Workbook integration is handled later by dedicated helper functions.
    """
    validation = DataValidation(
        type=validation_type.value,
        allowBlank=allow_blank,
    )

    if operator is not None:
        validation.operator = operator.value

    if formula1 is not None:
        if isinstance(formula1, str):
            formula1 = _escape_formula(formula1)
        validation.formula1 = formula1

    if formula2 is not None:
        if isinstance(formula2, str):
            formula2 = _escape_formula(formula2)
        validation.formula2 = formula2

    validation.promptTitle = prompt_title
    validation.prompt = prompt_message

    validation.errorTitle = error_title
    validation.error = error_message

    validation.showInputMessage = DEFAULT_SHOW_INPUT_MESSAGE
    validation.showErrorMessage = DEFAULT_SHOW_ERROR_MESSAGE

    validation.errorStyle = error_style.value

    return validation


def integer_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create an integer (whole number) validation.

    Parameters
    ----------
    minimum:
        Lower bound.

    maximum:
        Upper bound.

    operator:
        Excel comparison operator.

    allow_blank:
        Whether blank cells are allowed.

    prompt_title, prompt_message:
        Input message configuration.

    error_title, error_message:
        Error dialog configuration.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Configured validation object.

    Notes
    -----
    The meaning of ``minimum`` and ``maximum`` depends on the selected
    operator.

    Examples
    --------
    ::

        integer_validation(
            minimum=0,
            maximum=10
        )

        integer_validation(
            operator=Operator.GREATER_THAN,
            minimum=0
        )
    """
    if minimum is not None and not isinstance(minimum, int):
        raise TypeError("minimum must be an integer")

    if maximum is not None and not isinstance(maximum, int):
        raise TypeError("maximum must be an integer")

    if (
        operator == Operator.BETWEEN
        and minimum is not None
        and maximum is not None
        and minimum > maximum
    ):
        raise ValueError(
            "minimum cannot be greater than maximum"
        )

    return _build_validation(
        validation_type=ValidationType.WHOLE,
        operator=operator,
        formula1=minimum,
        formula2=maximum,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def whole_number_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a whole-number validation.

    This function is an explicit semantic alias of
    :func:`integer_validation`.

    The alias improves readability in workbook-generation code while
    keeping all implementation logic in a single location.

    Returns
    -------
    DataValidation
        Configured validation object.
    """
    return integer_validation(
        minimum=minimum,
        maximum=maximum,
        operator=operator,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def decimal_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a decimal-number validation.

    Unlike integer validation, decimal validation accepts both integer
    and floating-point values.

    Parameters
    ----------
    minimum:
        Lower numeric bound.

    maximum:
        Upper numeric bound.

    operator:
        Excel comparison operator.

    allow_blank:
        Whether blank cells are permitted.

    Returns
    -------
    DataValidation
        Configured validation object.

    Examples
    --------
    ::

        decimal_validation(
            minimum=0.0,
            maximum=100.0
        )

        decimal_validation(
            operator=Operator.LESS_THAN,
            maximum=1.5
        )
    """
    if minimum is not None and not isinstance(minimum, (int, float)):
        raise TypeError(
            "minimum must be numeric"
        )

    if maximum is not None and not isinstance(maximum, (int, float)):
        raise TypeError(
            "maximum must be numeric"
        )

    if (
        operator == Operator.BETWEEN
        and minimum is not None
        and maximum is not None
        and minimum > maximum
    ):
        raise ValueError(
            "minimum cannot exceed maximum"
        )

    return _build_validation(
        validation_type=ValidationType.DECIMAL,
        operator=operator,
        formula1=minimum,
        formula2=maximum,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


###############################################################################
# Dropdown Validation Builders (Part 4A)
###############################################################################

def list_validation(
    values: StringCollection,
    *,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create an Excel dropdown validation from an explicit list of values.

    This function is intended for relatively small lists that can be embedded
    directly into the validation formula.

    Excel stores explicit dropdowns as a quoted comma-separated string, for
    example::

        "Yes,No"

    Unfortunately Excel limits this string to approximately 255 characters.
    Longer lists must instead be stored in worksheet cells and referenced via
    a worksheet range or named range.

    Parameters
    ----------
    values:
        Sequence of dropdown values.

    allow_blank:
        Whether blank cells are permitted.

    prompt_title:
        Input prompt title.

    prompt_message:
        Input prompt message.

    error_title:
        Error dialog title.

    error_message:
        Error dialog message.

    error_style:
        Excel validation error style.

    Returns
    -------
    DataValidation
        Configured list validation.

    Raises
    ------
    TypeError
        If values is not an iterable collection.

    ValueError
        If the collection is empty.

    ValueError
        If the combined explicit list exceeds Excel's inline limit.

    Notes
    -----
    This function intentionally raises an exception for oversized lists rather
    than silently converting them into worksheet-based dropdowns. Workbook
    generation should explicitly decide where long lists are stored.
    """
    _validate_iterable(values, "values")

    cleaned: list[str] = []

    for value in values:
        text = str(value).strip()

        if not text:
            raise ValueError(
                "Dropdown values cannot contain empty strings."
            )

        if "," in text:
            raise ValueError(
                "Dropdown values cannot contain commas "
                "when using explicit Excel lists."
            )

        cleaned.append(text)

    formula = _excel_list(cleaned)

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def range_validation(
    *,
    sheet_name: str,
    cell_range: str,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation using a worksheet range.

    Examples
    --------
    ::

        range_validation(
            sheet_name="Lookup",
            cell_range="A2:A20",
        )

    Generates a validation referencing::

        Lookup!$A$2:$A$20

    If the worksheet name contains spaces or special characters it is
    automatically quoted.

    Parameters
    ----------
    sheet_name:
        Worksheet containing the dropdown values.

    cell_range:
        Excel range containing dropdown values.

    allow_blank:
        Whether blank values are permitted.

    Returns
    -------
    DataValidation
        Configured validation object.

    Notes
    -----
    This function performs only syntactic validation.

    It does not verify that the worksheet or cells actually exist.
    """
    reference = _build_formula_reference(
        sheet_name=sheet_name,
        cell_range=cell_range,
    )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=reference,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def named_range_validation(
    named_range: str,
    *,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation using an Excel named range.

    Named ranges are the preferred approach for large dropdowns because they

    * avoid Excel's 255-character explicit-list limitation,
    * automatically adapt when workbook layout changes,
    * improve readability of workbook formulas,
    * allow dynamic dropdowns.

    Parameters
    ----------
    named_range:
        Excel defined name.

    allow_blank:
        Whether blank values are allowed.

    prompt_title:
        Input prompt title.

    prompt_message:
        Input prompt.

    error_title:
        Error dialog title.

    error_message:
        Error dialog text.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Configured dropdown validation.

    Raises
    ------
    ValueError
        If the supplied name is not a syntactically valid Excel defined name.

    Examples
    --------
    ::

        named_range_validation("Teams")

        named_range_validation("PlayerNames")

    Notes
    -----
    This function validates only the syntax of the supplied name.

    Existence of the named range is verified later when the workbook is
    generated.
    """
    _validate_non_empty(named_range, "named_range")

    if not _is_named_range(named_range):
        raise ValueError(
            f"'{named_range}' is not a valid Excel named range."
        )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=named_range,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "list_validation",
        "range_validation",
        "named_range_validation",
    ]
)

###############################################################################
# Dropdown Validation Builders (Part 4B)
###############################################################################

def worksheet_range_validation(
    worksheet_name: str,
    cell_range: str,
    *,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation referencing a worksheet range.

    This function is primarily a semantic wrapper around
    :func:`range_validation`, improving readability when generating workbook
    layouts.

    Parameters
    ----------
    worksheet_name:
        Worksheet containing dropdown values.

    cell_range:
        Range containing dropdown entries.

    Returns
    -------
    DataValidation
        Configured list validation.

    Notes
    -----
    The worksheet is not validated for existence. Only the reference syntax is
    verified.
    """
    return range_validation(
        sheet_name=worksheet_name,
        cell_range=cell_range,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def dynamic_named_range_validation(
    named_range: str,
    *,
    use_offset: bool = False,
    height: FormulaValue = "COUNTA($A:$A)",
    width: FormulaValue = 1,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a validation referencing a dynamic named range.

    Dynamic ranges automatically expand or contract as source data changes.

    Two strategies are commonly used:

    1. Excel defined names that already contain OFFSET or INDEX formulas.
    2. Inline OFFSET formulas.

    Parameters
    ----------
    named_range:
        Base named range.

    use_offset:
        If False (recommended), reference the named range directly.

        If True, generate an OFFSET formula.

    height:
        OFFSET height.

    width:
        OFFSET width.

    Returns
    -------
    DataValidation
        Configured dropdown validation.

    Notes
    -----
    Using a workbook-defined dynamic named range is generally preferable to
    embedding OFFSET directly because:

    * workbook formulas remain readable
    * workbook recalculation is reduced
    * validation rules remain simpler
    """
    _validate_non_empty(named_range, "named_range")

    if not _is_named_range(named_range):
        raise ValueError(
            f"Invalid named range: {named_range}"
        )

    if use_offset:
        formula = (
            f"OFFSET({named_range},0,0,"
            f"{height},{width})"
        )
    else:
        formula = named_range

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def dependent_dropdown_validation(
    parent_cell: str,
    *,
    indirect: bool = True,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dependent dropdown validation.

    Dependent dropdowns are commonly used where one selection determines the
    available values in another.

    Cricket examples
    ----------------
    Team
        -> Players

    Tournament
        -> Matches

    Country
        -> Stadiums

    Parameters
    ----------
    parent_cell:
        Cell containing the parent selection.

    indirect:
        Whether to generate an INDIRECT formula.

    Returns
    -------
    DataValidation
        Configured validation.

    Notes
    -----
    Excel's INDIRECT function interprets the value of the parent cell as the
    name of another range.

    Example
    -------

    If A2 contains::

        India

    then

    ::

        =INDIRECT($A$2)

    references the named range called ``India``.

    This is the standard mechanism used for cascading dropdowns in Excel.
    """
    absolute_parent = _absolute_cell(parent_cell)

    if indirect:
        formula = f"INDIRECT({absolute_parent})"
    else:
        formula = absolute_parent

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "worksheet_range_validation",
        "dynamic_named_range_validation",
        "dependent_dropdown_validation",
    ]
)


###############################################################################
# Dropdown Validation Builders (Part 4B-1)
#
# This section introduces helpers for worksheet-backed and dynamically-sized
# dropdown lists. All functions remain workbook-independent and merely build
# DataValidation objects.
###############################################################################

def _build_list_formula(
    *,
    explicit_values: StringCollection | None = None,
    worksheet: str | None = None,
    cell_range: str | None = None,
    named_range: str | None = None,
    formula: str | None = None,
) -> str:
    """
    Build the Excel formula used by a list validation.

    Exactly one source must be supplied.

    Supported sources
    -----------------
    1. Explicit list
    2. Worksheet range
    3. Named range
    4. Raw Excel formula

    This helper exists so every dropdown builder constructs formulas in a
    consistent manner.

    Parameters
    ----------
    explicit_values:
        Values for an inline Excel dropdown.

    worksheet:
        Worksheet containing dropdown values.

    cell_range:
        Cell range containing dropdown values.

    named_range:
        Excel defined name.

    formula:
        Raw Excel formula.

    Returns
    -------
    str
        Formula suitable for DataValidation.formula1.

    Raises
    ------
    ValueError
        If zero or multiple sources are supplied.
    """
    supplied = sum(
        value is not None
        for value in (
            explicit_values,
            worksheet,
            named_range,
            formula,
        )
    )

    if supplied != 1:
        raise ValueError(
            "Exactly one validation source must be supplied."
        )

    if explicit_values is not None:
        return _excel_list(explicit_values)

    if worksheet is not None:
        if cell_range is None:
            raise ValueError(
                "cell_range is required when worksheet is supplied."
            )

        return _build_formula_reference(
            worksheet,
            cell_range,
        )

    if named_range is not None:
        _validate_non_empty(named_range, "named_range")

        if not _is_named_range(named_range):
            raise ValueError(
                f"Invalid named range: {named_range}"
            )

        return named_range

    assert formula is not None

    return _escape_formula(formula)


def _offset_formula(
    *,
    reference: str,
    rows: FormulaValue = 0,
    columns: FormulaValue = 0,
    height: FormulaValue = 1,
    width: FormulaValue = 1,
) -> str:
    """
    Build an Excel OFFSET formula.

    Examples
    --------
    OFFSET(Teams,0,0,COUNTA(Teams),1)

    Parameters
    ----------
    reference:
        Starting reference.

    rows:
        Row offset.

    columns:
        Column offset.

    height:
        Resulting range height.

    width:
        Resulting range width.

    Returns
    -------
    str
        OFFSET formula.
    """
    _validate_non_empty(reference, "reference")

    return (
        f"OFFSET("
        f"{reference},"
        f"{rows},"
        f"{columns},"
        f"{height},"
        f"{width}"
        f")"
    )


def worksheet_range_validation(
    *,
    worksheet: str,
    cell_range: str,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation referencing a worksheet range.

    This function is the preferred way of creating dropdowns backed by lookup
    sheets because worksheet references have no practical size limitation,
    unlike Excel's inline list validation.

    Parameters
    ----------
    worksheet:
        Worksheet containing dropdown values.

    cell_range:
        Absolute or relative Excel range.

    Returns
    -------
    DataValidation
        Configured list validation.

    Notes
    -----
    Worksheet names are automatically quoted when required.

    Cell ranges are converted into absolute references.

    Examples
    --------
    ::

        worksheet_range_validation(
            worksheet="Lookup",
            cell_range="A2:A200",
        )

    Produces::

        Lookup!$A$2:$A$200
    """
    formula = _build_list_formula(
        worksheet=worksheet,
        cell_range=cell_range,
    )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def dynamic_named_range_validation(
    *,
    named_range: str,
    use_offset: bool = False,
    offset_rows: FormulaValue = 0,
    offset_columns: FormulaValue = 0,
    height: FormulaValue = 1,
    width: FormulaValue = 1,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a validation backed by a dynamic named range.

    Two strategies are supported.

    Strategy 1 (recommended)
    ------------------------
    Reference a workbook-defined dynamic named range directly.

    Example::

        Players

    Strategy 2
    ----------
    Construct an OFFSET formula dynamically.

    Example::

        OFFSET(
            Players,
            0,
            0,
            COUNTA(Players),
            1
        )

    Parameters
    ----------
    named_range:
        Workbook defined name.

    use_offset:
        Whether to wrap the reference in OFFSET().

    offset_rows:
        Row displacement.

    offset_columns:
        Column displacement.

    height:
        Resulting range height.

    width:
        Resulting range width.

    Returns
    -------
    DataValidation
        Configured dropdown validation.
    """
    _validate_non_empty(named_range, "named_range")

    if not _is_named_range(named_range):
        raise ValueError(
            f"'{named_range}' is not a valid Excel named range."
        )

    if use_offset:
        formula = _offset_formula(
            reference=named_range,
            rows=offset_rows,
            columns=offset_columns,
            height=height,
            width=width,
        )
    else:
        formula = _build_list_formula(
            named_range=named_range,
        )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )



###############################################################################
# Cricket Validation Factories (Part 5A)
###############################################################################

def player_name_validation(
    player_names: StringCollection,
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for selecting a player.

    This factory is intended for batting, bowling, fielding, captain,
    wicketkeeper, and substitute selection throughout the workbook.

    Parameters
    ----------
    player_names:
        Collection of player names available for selection.

    defaults:
        Default validation configuration.

    Returns
    -------
    DataValidation
        Configured player-name dropdown.

    Raises
    ------
    ValueError
        If the collection is empty.

    Notes
    -----
    This function is intentionally workbook-independent.

    It accepts the player names directly rather than referencing any
    worksheet or named range.

    For large tournaments containing many players, callers should instead
    use ``named_range_validation()`` or
    ``worksheet_range_validation()``.
    """
    _validate_iterable(player_names, "player_names")

    values = tuple(str(name).strip() for name in player_names)

    if not values:
        raise ValueError("player_names cannot be empty.")

    return list_validation(
        values,
        allow_blank=defaults.allow_blank,
        prompt_title="Player",
        prompt_message="Select a player.",
        error_title=defaults.error_title,
        error_message="Please select a valid player.",
        error_style=ErrorStyle.STOP,
    )


def team_name_validation(
    team_names: StringCollection,
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for selecting a cricket team.

    Parameters
    ----------
    team_names:
        Available team names.

    defaults:
        Default validation configuration.

    Returns
    -------
    DataValidation
        Configured team dropdown.

    Notes
    -----
    Suitable for:

    * Home team
    * Away team
    * Toss winner
    * Batting team
    * Bowling team
    """
    _validate_iterable(team_names, "team_names")

    values = tuple(str(team).strip() for team in team_names)

    if not values:
        raise ValueError("team_names cannot be empty.")

    return list_validation(
        values,
        allow_blank=defaults.allow_blank,
        prompt_title="Team",
        prompt_message="Select a team.",
        error_title=defaults.error_title,
        error_message="Please select a valid team.",
        error_style=ErrorStyle.STOP,
    )


def yes_no_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a reusable Yes/No dropdown.

    This validator is intentionally generic and can be reused for
    numerous workbook fields including:

    * Super Over
    * Match Abandoned
    * Follow-on
    * Powerplay Active
    * Duckworth-Lewis Applied
    * Review Taken

    Returns
    -------
    DataValidation
        Configured Yes/No dropdown.
    """
    return list_validation(
        YES_NO_OPTIONS,
        allow_blank=defaults.allow_blank,
        prompt_title="Confirmation",
        prompt_message="Select Yes or No.",
        error_title=defaults.error_title,
        error_message="Please choose Yes or No.",
        error_style=ErrorStyle.STOP,
    )


def toss_decision_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown for the toss decision.

    Available values

    * Bat
    * Bowl

    Returns
    -------
    DataValidation
        Configured toss-decision dropdown.

    Notes
    -----
    These values follow the terminology used by the
    International Cricket Council (ICC).
    """
    return list_validation(
        TOSS_DECISIONS,
        allow_blank=defaults.allow_blank,
        prompt_title="Toss Decision",
        prompt_message="Select the toss decision.",
        error_title=defaults.error_title,
        error_message="Select Bat or Bowl.",
        error_style=ErrorStyle.STOP,
    )


def match_result_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown for recording the official match result.

    Supported values
    ----------------
    * Team Won
    * Tie
    * No Result
    * Abandoned

    Returns
    -------
    DataValidation
        Configured match-result dropdown.

    Notes
    -----
    This validator records only the category of result.

    The winning team should be recorded separately using
    ``team_name_validation()``.
    """
    return list_validation(
        (
            "Team Won",
            "Tie",
            "No Result",
            "Abandoned",
        ),
        allow_blank=defaults.allow_blank,
        prompt_title="Match Result",
        prompt_message="Select the official match result.",
        error_title=defaults.error_title,
        error_message="Please select a valid match result.",
        error_style=ErrorStyle.STOP,
    )


###############################################################################
# Public API
###############################################################################

__all__.extend(
    [
        "player_name_validation",
        "team_name_validation",
        "yes_no_validation",
        "toss_decision_validation",
        "match_result_validation",
    ]
)



###############################################################################
# Cricket Validation Factories (Part 5B)
###############################################################################

def dismissal_type_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for wicket dismissal types.

    Supported dismissal methods follow standard Laws of Cricket terminology
    commonly used in scorebooks and scoring software.

    Values
    ------
    Bowled
    Caught
    LBW
    Run Out
    Stumped
    Hit Wicket
    Obstructing the Field
    Timed Out
    Hit the Ball Twice
    Retired Out
    Retired Hurt

    Returns
    -------
    DataValidation
        Configured dismissal-type dropdown.
    """
    return list_validation(
        DISMISSAL_TYPES,
        allow_blank=defaults.allow_blank,
        prompt_title="Dismissal Type",
        prompt_message="Select the method of dismissal.",
        error_title=defaults.error_title,
        error_message="Select a valid dismissal type.",
        error_style=ErrorStyle.STOP,
    )


def extra_type_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for cricket extras.

    Supported values
    ----------------
    None
    Bye
    Leg Bye
    Wide
    No Ball
    Penalty

    Returns
    -------
    DataValidation
        Configured extras dropdown.

    Notes
    -----
    "None" represents a legal delivery with no extras awarded.
    """
    return list_validation(
        EXTRA_TYPES,
        allow_blank=defaults.allow_blank,
        prompt_title="Extra Type",
        prompt_message="Select the type of extra awarded.",
        error_title=defaults.error_title,
        error_message="Please select a valid extra type.",
        error_style=ErrorStyle.STOP,
    )


def legal_delivery_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a Yes/No dropdown indicating whether the delivery is legal.

    This validation is intentionally independent of the recorded extra
    because some scoring systems determine legality before calculating
    innings progression.

    Values
    ------
    Yes
    No

    Returns
    -------
    DataValidation
        Configured legal-delivery dropdown.
    """
    return list_validation(
        YES_NO_OPTIONS,
        allow_blank=defaults.allow_blank,
        prompt_title="Legal Delivery",
        prompt_message="Was this a legal delivery?",
        error_title=defaults.error_title,
        error_message="Select Yes or No.",
        error_style=ErrorStyle.STOP,
    )


def ball_outcome_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown describing the overall outcome of a delivery.

    The values intentionally describe the primary scoring event for the
    delivery. Additional detail (runs, dismissal type, extras, etc.) should
    be captured using their dedicated validation fields.

    Supported values
    ----------------
    Dot Ball
    Runs
    Boundary Four
    Six
    Wicket
    Wide
    No Ball
    Bye
    Leg Bye
    Penalty

    Returns
    -------
    DataValidation
        Configured ball-outcome dropdown.
    """
    return list_validation(
        BALL_OUTCOMES,
        allow_blank=defaults.allow_blank,
        prompt_title="Ball Outcome",
        prompt_message="Select the primary outcome of the delivery.",
        error_title=defaults.error_title,
        error_message="Please select a valid ball outcome.",
        error_style=ErrorStyle.STOP,
    )


def drs_result_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown for Decision Review System (DRS) outcomes.

    Supported values
    ----------------
    Not Reviewed
    Upheld
    Overturned
    Umpire's Call

    Returns
    -------
    DataValidation
        Configured DRS-result dropdown.

    Notes
    -----
    "Not Reviewed" allows the field to remain meaningful without relying on
    blank cells.
    """
    return list_validation(
        DRS_RESULTS,
        allow_blank=defaults.allow_blank,
        prompt_title="DRS Result",
        prompt_message="Select the DRS outcome.",
        error_title=defaults.error_title,
        error_message="Please select a valid DRS result.",
        error_style=ErrorStyle.STOP,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "dismissal_type_validation",
        "extra_type_validation",
        "legal_delivery_validation",
        "ball_outcome_validation",
        "drs_result_validation",
    ]
)

###############################################################################
# Cricket Validation Factories (Part 5C)
###############################################################################

def over_number_validation(
    *,
    maximum_overs: int = 50,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a validation for the over number.

    The over number represents the completed over count within an innings.

    Parameters
    ----------
    maximum_overs:
        Maximum overs permitted in the match format.

        Typical values:

        * 20  -> T20
        * 50  -> ODI
        * 90+ -> Multi-day cricket

    defaults:
        Shared validation defaults.

    Returns
    -------
    DataValidation
        Integer validation permitting values from 0 to
        ``maximum_overs``.

    Raises
    ------
    ValueError
        If ``maximum_overs`` is less than one.
    """
    if maximum_overs < 1:
        raise ValueError(
            "maximum_overs must be greater than zero."
        )

    return whole_number_validation(
        minimum=0,
        maximum=maximum_overs,
        allow_blank=defaults.allow_blank,
        prompt_title="Over Number",
        prompt_message="Enter the completed over number.",
        error_title=defaults.error_title,
        error_message=(
            f"Over number must be between 0 and "
            f"{maximum_overs}."
        ),
        error_style=ErrorStyle.STOP,
    )


def ball_number_validation(
    *,
    balls_per_over: int = 6,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a validation for the legal ball number within an over.

    Cricket scoring normally records legal deliveries numbered from
    1 through 6.

    Parameters
    ----------
    balls_per_over:
        Number of legal deliveries in an over.

    defaults:
        Shared validation defaults.

    Returns
    -------
    DataValidation
        Integer validation.

    Notes
    -----
    This validation applies only to legal deliveries.

    Wides and No Balls are represented separately by the scoring
    engine and therefore do not require extending the numeric range.
    """
    if balls_per_over < 1:
        raise ValueError(
            "balls_per_over must be greater than zero."
        )

    return whole_number_validation(
        minimum=1,
        maximum=balls_per_over,
        allow_blank=defaults.allow_blank,
        prompt_title="Ball Number",
        prompt_message="Enter the legal delivery number.",
        error_title=defaults.error_title,
        error_message=(
            f"Ball number must be between 1 and "
            f"{balls_per_over}."
        ),
        error_style=ErrorStyle.STOP,
    )


def runs_scored_validation(
    *,
    maximum_runs: int = 7,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a validation for runs scored from a single delivery.

    Parameters
    ----------
    maximum_runs:
        Upper limit accepted by the validation.

    defaults:
        Shared validation defaults.

    Returns
    -------
    DataValidation
        Whole-number validation.

    Notes
    -----
    A default maximum of seven supports the overwhelming majority
    of deliveries:

    * Dot ball
    * Singles
    * Twos
    * Threes
    * Four
    * Five
    * Six
    * Seven (rare overthrow scenarios)

    Larger totals resulting from multiple overthrows can still be
    supported by increasing ``maximum_runs``.
    """
    if maximum_runs < 0:
        raise ValueError(
            "maximum_runs cannot be negative."
        )

    return whole_number_validation(
        minimum=0,
        maximum=maximum_runs,
        allow_blank=defaults.allow_blank,
        prompt_title="Runs",
        prompt_message="Enter runs scored from the delivery.",
        error_title=defaults.error_title,
        error_message=(
            f"Runs must be between 0 and "
            f"{maximum_runs}."
        ),
        error_style=ErrorStyle.STOP,
    )


def wicket_count_validation(
    *,
    maximum_wickets: int = 10,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a validation for wickets fallen.

    Parameters
    ----------
    maximum_wickets:
        Maximum wickets permitted in an innings.

    defaults:
        Shared validation defaults.

    Returns
    -------
    DataValidation
        Whole-number validation.

    Notes
    -----
    Standard cricket innings end after ten wickets have fallen,
    making ten the default upper bound.
    """
    if maximum_wickets < 1:
        raise ValueError(
            "maximum_wickets must be greater than zero."
        )

    return whole_number_validation(
        minimum=0,
        maximum=maximum_wickets,
        allow_blank=defaults.allow_blank,
        prompt_title="Wickets",
        prompt_message="Enter wickets fallen.",
        error_title=defaults.error_title,
        error_message=(
            f"Wickets must be between 0 and "
            f"{maximum_wickets}."
        ),
        error_style=ErrorStyle.STOP,
    )


def innings_number_validation(
    *,
    maximum_innings: int = 4,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a validation for the innings number.

    Parameters
    ----------
    maximum_innings:
        Maximum innings supported.

        Typical values:

        * 2 -> Limited overs cricket
        * 4 -> First-class cricket

    defaults:
        Shared validation defaults.

    Returns
    -------
    DataValidation
        Whole-number validation.

    Raises
    ------
    ValueError
        If ``maximum_innings`` is less than one.
    """
    if maximum_innings < 1:
        raise ValueError(
            "maximum_innings must be greater than zero."
        )

    return whole_number_validation(
        minimum=1,
        maximum=maximum_innings,
        allow_blank=defaults.allow_blank,
        prompt_title="Innings",
        prompt_message="Select the innings number.",
        error_title=defaults.error_title,
        error_message=(
            f"Innings must be between 1 and "
            f"{maximum_innings}."
        ),
        error_style=ErrorStyle.STOP,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "over_number_validation",
        "ball_number_validation",
        "runs_scored_validation",
        "wicket_count_validation",
        "innings_number_validation",
    ]
)

###############################################################################
# Cricket Validation Factories (Part 5D)
###############################################################################

def batting_style_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for a batter's batting style.

    Supported values
    ----------------
    Right-hand Bat
    Left-hand Bat

    Returns
    -------
    DataValidation
        Configured batting-style dropdown.

    Notes
    -----
    These values follow the terminology commonly used by the
    International Cricket Council (ICC), domestic scorebooks,
    and most electronic scoring systems.
    """
    return list_validation(
        BATTING_STYLES,
        allow_blank=defaults.allow_blank,
        prompt_title="Batting Style",
        prompt_message="Select the batter's batting style.",
        error_title=defaults.error_title,
        error_message="Please select a valid batting style.",
        error_style=ErrorStyle.STOP,
    )


def bowling_style_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for a bowler's bowling style.

    Supported values
    ----------------
    Right-arm Fast
    Right-arm Fast Medium
    Right-arm Medium Fast
    Right-arm Medium
    Right-arm Off Break
    Right-arm Leg Break
    Right-arm Leg Spin
    Right-arm Googly
    Left-arm Fast
    Left-arm Fast Medium
    Left-arm Medium Fast
    Left-arm Medium
    Left-arm Orthodox
    Left-arm Wrist Spin

    Returns
    -------
    DataValidation
        Configured bowling-style dropdown.

    Notes
    -----
    These options represent the most commonly recorded bowling
    classifications used in professional cricket.
    """
    return list_validation(
        BOWLING_STYLES,
        allow_blank=defaults.allow_blank,
        prompt_title="Bowling Style",
        prompt_message="Select the bowler's bowling style.",
        error_title=defaults.error_title,
        error_message="Please select a valid bowling style.",
        error_style=ErrorStyle.STOP,
    )


def powerplay_selection_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation for the active powerplay.

    Supported values
    ----------------
    None
    Mandatory
    Batting
    Bowling

    Returns
    -------
    DataValidation
        Configured powerplay dropdown.

    Notes
    -----
    Different competitions use different powerplay rules. This validation
    intentionally captures only the category rather than competition-specific
    over ranges.
    """
    return list_validation(
        POWERPLAY_OPTIONS,
        allow_blank=defaults.allow_blank,
        prompt_title="Powerplay",
        prompt_message="Select the applicable powerplay.",
        error_title=defaults.error_title,
        error_message="Please select a valid powerplay.",
        error_style=ErrorStyle.STOP,
    )


def no_ball_reason_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation describing why a delivery was called
    a No Ball.

    Supported values
    ----------------
    Front Foot
    Back Foot
    Above Waist Full Toss
    Dangerous Short Ball
    Throwing
    Multiple Bounce
    Breaking Wicket
    Fielder Position
    Keeper Position
    Other

    Returns
    -------
    DataValidation
        Configured No Ball reason dropdown.

    Notes
    -----
    The categories are intentionally broad so they remain applicable across
    different playing conditions and competition regulations.
    """
    return list_validation(
        NO_BALL_REASONS,
        allow_blank=defaults.allow_blank,
        prompt_title="No Ball Reason",
        prompt_message="Select the reason for the No Ball.",
        error_title=defaults.error_title,
        error_message="Please select a valid No Ball reason.",
        error_style=ErrorStyle.STOP,
    )


def wide_reason_validation(
    *,
    defaults: ValidationDefaults = ValidationDefaults(),
) -> DataValidation:
    """
    Create a dropdown validation describing why a delivery was called
    Wide.

    Supported values
    ----------------
    Off Side
    Leg Side
    Above Head
    Passed Batter
    Other

    Returns
    -------
    DataValidation
        Configured Wide reason dropdown.

    Notes
    -----
    These values are intended for scoring and analysis rather than
    umpire decision-making, allowing tournaments to record the general
    cause of wides consistently.
    """
    return list_validation(
        WIDE_REASONS,
        allow_blank=defaults.allow_blank,
        prompt_title="Wide Reason",
        prompt_message="Select the reason for the Wide.",
        error_title=defaults.error_title,
        error_message="Please select a valid Wide reason.",
        error_style=ErrorStyle.STOP,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "batting_style_validation",
        "bowling_style_validation",
        "powerplay_selection_validation",
        "no_ball_reason_validation",
        "wide_reason_validation",
    ]
)
__all__.extend(
    [
        "YES_NO_OPTIONS",
        "TOSS_DECISIONS",
        "MATCH_RESULTS",
        "DISMISSAL_TYPES",
        "EXTRA_TYPES",
        "BALL_OUTCOMES",
        "DRS_RESULTS",
        "BATTING_STYLES",
        "BOWLING_STYLES",
        "POWERPLAY_OPTIONS",
        "NO_BALL_REASONS",
        "WIDE_REASONS",
    ]
)