"""
validation.py
=============

Reusable Excel Validation Utilities
===================================

This module provides a workbook-independent abstraction for creating and
managing validation rules used throughout the Cricket Tournament Manager.

The primary objective is to keep *validation definitions* separate from
*worksheet layout*. A validation should describe **what is allowed**, while
modules such as ``workbook.py`` decide **where** that validation is applied.

Why this module exists
----------------------

Excel's Data Validation system is powerful but verbose. Creating validation
objects repeatedly throughout the codebase leads to:

    • duplicated logic
    • inconsistent prompts
    • inconsistent error messages
    • workbook-specific implementations
    • difficult testing
    • difficult migration to future platforms

Instead, this module acts as a centralized factory for validation rules.

Design Goals
------------

This module is designed around several long-term principles.

1. Workbook Independence
~~~~~~~~~~~~~~~~~~~~~~~~
This module must never depend on worksheet names, workbook layouts,
table names, or cell coordinates hardcoded elsewhere.

2. Deterministic Behaviour
~~~~~~~~~~~~~~~~~~~~~~~~~~
Every function should return the same result given the same inputs.

No hidden state.

No global workbook references.

No side effects.

3. Future Web Compatibility
~~~~~~~~~~~~~~~~~~~~~~~~~~~
Although the initial implementation targets Microsoft Excel through
openpyxl, the validation definitions themselves should remain generic.

Future implementations should be able to translate these validation
definitions into:

    • HTML forms
    • REST API validation
    • React forms
    • Android forms
    • iOS forms
    • desktop applications

without rewriting business rules.

4. Reusability
~~~~~~~~~~~~~~
All validation builders should be generic enough that they can be reused
outside of cricket scoring.

Example:

Instead of:

    create_team_dropdown()

prefer:

    list_validation(...)

with higher-level cricket-specific wrappers implemented separately.

5. Explicit Configuration
~~~~~~~~~~~~~~~~~~~~~~~~~
Every validation should be configured explicitly.

Hidden defaults should be avoided wherever possible.

6. Testability
~~~~~~~~~~~~~~
This module should be easy to unit test without constructing an Excel
workbook.

Relationship to Other Modules
-----------------------------

formulas.py
    Provides deterministic mathematical calculations.

validation.py
    Creates reusable validation definitions.

workbook.py
    Applies validation rules to workbook cells.

create_match.py
    Uses validation builders when generating score sheets.

score_ball.py
    Relies on workbook validations to ensure legal user input.

Architecture Overview
---------------------

This module will eventually contain several layers.

Layer 1
    Internal helper utilities.

Layer 2
    Generic validation builders.

Layer 3
    Dropdown builders.

Layer 4
    Cricket-specific validation factories.

Layer 5
    Workbook integration helpers.

Only Layers 4 and 5 should know anything about cricket terminology.

Version
-------
Initial development version.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Final
from typing import Iterable
from typing import Optional
from typing import Sequence
from typing import TypeAlias
from typing import Union

from openpyxl.worksheet.datavalidation import DataValidation

###############################################################################
# Type Aliases
###############################################################################

#: Acceptable numeric types used throughout validation builders.
Number: TypeAlias = Union[int, float]

#: Value accepted by Excel validation formulas.
FormulaValue: TypeAlias = Union[str, Number]

#: Collection of string values used for dropdowns.
StringCollection: TypeAlias = Sequence[str]

#: Generic iterable of values.
ValueIterable: TypeAlias = Iterable[FormulaValue]

#: Optional formula parameter.
OptionalFormula: TypeAlias = Optional[FormulaValue]

###############################################################################
# Module Constants
###############################################################################

#: Default Excel prompt title shown when a validated cell is selected.
#
# Centralising this string ensures a consistent user experience across
# every worksheet generated by the application.
DEFAULT_PROMPT_TITLE: Final[str] = "Input Required"

#: Default prompt message.
#
# Individual validators may override this with more specific guidance.
DEFAULT_PROMPT_MESSAGE: Final[str] = (
    "Please enter a valid value."
)

#: Default error title displayed when validation fails.
#
# Using a consistent title makes workbook behaviour predictable.
DEFAULT_ERROR_TITLE: Final[str] = "Invalid Input"

#: Default error message displayed when invalid data is entered.
DEFAULT_ERROR_MESSAGE: Final[str] = (
    "The value entered does not satisfy the validation rules."
)

#: Whether blank cells should be accepted by default.
#
# Blank values are often required while a match is in progress.
DEFAULT_ALLOW_BLANK: Final[bool] = True

#: Whether Excel should display the input prompt.
DEFAULT_SHOW_INPUT_MESSAGE: Final[bool] = True

#: Whether Excel should display an error alert.
DEFAULT_SHOW_ERROR_MESSAGE: Final[bool] = True

#: Maximum number of characters supported by an explicit Excel list.
#
# Longer lists require worksheet ranges or named ranges.
EXCEL_INLINE_LIST_LIMIT: Final[int] = 255

#: Maximum worksheet name length supported by Excel.
EXCEL_MAX_SHEET_NAME_LENGTH: Final[int] = 31

#: Maximum cell text length supported by Excel.
EXCEL_MAX_CELL_TEXT_LENGTH: Final[int] = 32767

###############################################################################
# Default Configuration
###############################################################################


@dataclass(frozen=True, slots=True)
class ValidationDefaults:
    """
    Immutable default configuration shared by validation builders.

    This dataclass intentionally contains only generic configuration
    independent of any workbook structure.

    Individual validation factory functions may override any value.
    """

    allow_blank: bool = DEFAULT_ALLOW_BLANK
    show_input_message: bool = DEFAULT_SHOW_INPUT_MESSAGE
    show_error_message: bool = DEFAULT_SHOW_ERROR_MESSAGE

    prompt_title: str = DEFAULT_PROMPT_TITLE
    prompt_message: str = DEFAULT_PROMPT_MESSAGE

    error_title: str = DEFAULT_ERROR_TITLE
    error_message: str = DEFAULT_ERROR_MESSAGE


###############################################################################
# Validation Types
###############################################################################


class ValidationType(str, Enum):
    """
    Supported Excel validation categories.

    These names intentionally mirror Excel terminology wherever practical,
    making future translation to other platforms straightforward.
    """

    #: Whole number validation.
    WHOLE = "whole"

    #: Decimal number validation.
    DECIMAL = "decimal"

    #: Explicit list or dropdown validation.
    LIST = "list"

    #: Date validation.
    DATE = "date"

    #: Time validation.
    TIME = "time"

    #: Text length validation.
    TEXT_LENGTH = "textLength"

    #: Arbitrary Excel formula validation.
    CUSTOM = "custom"

    #: Accept any value.
    #
    # Mostly useful when dynamically enabling/disabling validation.
    ANY = "any"


###############################################################################
# Comparison Operators
###############################################################################


class Operator(str, Enum):
    """
    Excel comparison operators.

    These operators are reused by multiple validation types including
    numeric, date, time and text-length validations.
    """

    BETWEEN = "between"
    NOT_BETWEEN = "notBetween"

    EQUAL = "equal"
    NOT_EQUAL = "notEqual"

    GREATER_THAN = "greaterThan"
    GREATER_THAN_OR_EQUAL = "greaterThanOrEqual"

    LESS_THAN = "lessThan"
    LESS_THAN_OR_EQUAL = "lessThanOrEqual"


###############################################################################
# Excel Error Styles
###############################################################################


class ErrorStyle(str, Enum):
    """
    Excel validation error styles.

    STOP
        Reject invalid input completely.

    WARNING
        Warn the user but permit override.

    INFORMATION
        Display informational message only.
    """

    STOP = "stop"
    WARNING = "warning"
    INFORMATION = "information"


###############################################################################
# Public API
###############################################################################

__all__ = [
    # Type aliases
    "Number",
    "FormulaValue",
    "StringCollection",
    "ValueIterable",
    "OptionalFormula",
    # Constants
    "DEFAULT_PROMPT_TITLE",
    "DEFAULT_PROMPT_MESSAGE",
    "DEFAULT_ERROR_TITLE",
    "DEFAULT_ERROR_MESSAGE",
    "DEFAULT_ALLOW_BLANK",
    "DEFAULT_SHOW_INPUT_MESSAGE",
    "DEFAULT_SHOW_ERROR_MESSAGE",
    "EXCEL_INLINE_LIST_LIMIT",
    "EXCEL_MAX_SHEET_NAME_LENGTH",
    "EXCEL_MAX_CELL_TEXT_LENGTH",
    # Dataclasses
    "ValidationDefaults",
    # Enums
    "ValidationType",
    "Operator",
    "ErrorStyle",
    # Future public builders
    "integer_validation",
    "decimal_validation",
    "whole_number_validation",
    "text_length_validation",
    "date_validation",
    "time_validation",
    "custom_formula_validation",
    "list_validation",
    "named_range_validation",
    "worksheet_range_validation",
    "dependent_dropdown_validation",
    "apply_validation",
    "apply_to_cells",
    "apply_to_range",
    "create_named_range",
]


###############################################################################
# Internal Helper Functions
###############################################################################

from collections.abc import Iterable
from openpyxl.utils import get_column_letter
from openpyxl.utils.cell import (
    absolute_coordinate,
    coordinate_from_string,
    range_boundaries,
)


def _quote_sheet_name(sheet_name: str) -> str:
    """
    Return a worksheet name safely quoted for use inside Excel formulas.

    Excel requires worksheet names containing spaces or special characters
    to be enclosed in single quotes.

    Any embedded single quote characters are escaped by doubling them.

    Examples
    --------
    >>> _quote_sheet_name("Scorecard")
    'Scorecard'

    >>> _quote_sheet_name("Team A")
    "'Team A'"

    >>> _quote_sheet_name("Bob's Team")
    "'Bob''s Team'"

    Parameters
    ----------
    sheet_name:
        Worksheet name.

    Returns
    -------
    str
        Properly quoted worksheet name suitable for Excel formulas.

    Raises
    ------
    TypeError
        If sheet_name is not a string.

    ValueError
        If sheet_name is empty.
    """
    _validate_non_empty(sheet_name, "sheet_name")

    escaped = sheet_name.replace("'", "''")

    requires_quotes = any(
        (
            ch.isspace()
            or ch in "[]:*?/\\-+&(){}.,"
            for ch in escaped
        )
    )

    if requires_quotes:
        return f"'{escaped}'"

    return escaped


def _absolute_cell(cell_reference: str) -> str:
    """
    Convert a cell reference into an absolute Excel reference.

    Examples
    --------
    >>> _absolute_cell("A1")
    '$A$1'

    >>> _absolute_cell("c15")
    '$C$15'

    Parameters
    ----------
    cell_reference:
        Excel cell reference.

    Returns
    -------
    str
        Absolute cell reference.

    Raises
    ------
    TypeError
        If the reference is not a string.

    ValueError
        If the reference is invalid.
    """
    _validate_non_empty(cell_reference, "cell_reference")

    try:
        coordinate_from_string(cell_reference.upper())
    except ValueError as exc:
        raise ValueError(
            f"Invalid cell reference: {cell_reference}"
        ) from exc

    return absolute_coordinate(cell_reference.upper())


def _absolute_range(range_reference: str) -> str:
    """
    Convert an Excel range into an absolute range.

    Examples
    --------
    >>> _absolute_range("A1:C5")
    '$A$1:$C$5'

    Parameters
    ----------
    range_reference:
        Excel range.

    Returns
    -------
    str
        Absolute Excel range.

    Raises
    ------
    ValueError
        If the range is invalid.
    """
    _validate_non_empty(range_reference, "range_reference")

    try:
        min_col, min_row, max_col, max_row = range_boundaries(
            range_reference
        )
    except ValueError as exc:
        raise ValueError(
            f"Invalid Excel range: {range_reference}"
        ) from exc

    return (
        f"${get_column_letter(min_col)}${min_row}:"
        f"${get_column_letter(max_col)}${max_row}"
    )


def _column_letter(column: int) -> str:
    """
    Convert a 1-based column number into its Excel letter.

    Examples
    --------
    >>> _column_letter(1)
    'A'

    >>> _column_letter(27)
    'AA'

    Parameters
    ----------
    column:
        One-based column index.

    Returns
    -------
    str
        Excel column letters.

    Raises
    ------
    ValueError
        If the column index is less than one.
    """
    if not isinstance(column, int):
        raise TypeError("column must be an integer")

    if column < 1:
        raise ValueError("column must be >= 1")

    return get_column_letter(column)


def _excel_list(values: StringCollection) -> str:
    """
    Convert an iterable of strings into an Excel inline list.

    Excel stores explicit dropdown lists as a comma-separated string.

    Examples
    --------
    >>> _excel_list(["Yes", "No"])
    '"Yes,No"'

    Parameters
    ----------
    values:
        Sequence of values.

    Returns
    -------
    str
        Excel list formula.

    Raises
    ------
    ValueError
        If the resulting string exceeds Excel's inline limit.
    """
    _validate_iterable(values, "values")

    items = [str(v).strip() for v in values]

    if not items:
        raise ValueError("values cannot be empty")

    joined = ",".join(items)

    if len(joined) > EXCEL_INLINE_LIST_LIMIT:
        raise ValueError(
            "Explicit Excel lists cannot exceed "
            f"{EXCEL_INLINE_LIST_LIMIT} characters."
        )

    return f'"{joined}"'


def _escape_formula(formula: str) -> str:
    """
    Normalise an Excel formula.

    Removes leading '=' if present and trims whitespace.

    Parameters
    ----------
    formula:
        Excel formula.

    Returns
    -------
    str
        Clean formula.
    """
    _validate_non_empty(formula, "formula")

    formula = formula.strip()

    if formula.startswith("="):
        formula = formula[1:]

    return formula


def _validate_non_empty(value: str, name: str) -> None:
    """
    Validate that a string is non-empty.

    Parameters
    ----------
    value:
        String value.

    name:
        Parameter name used in exception messages.

    Raises
    ------
    TypeError
        If value is not a string.

    ValueError
        If value is empty or whitespace.
    """
    if not isinstance(value, str):
        raise TypeError(f"{name} must be a string")

    if not value.strip():
        raise ValueError(f"{name} cannot be empty")


def _validate_iterable(values: Iterable, name: str) -> None:
    """
    Validate an iterable.

    Strings are explicitly rejected because they are iterable but almost
    never represent a collection of dropdown values.

    Parameters
    ----------
    values:
        Iterable object.

    name:
        Parameter name.

    Raises
    ------
    TypeError
        If values is not an iterable collection.
    """
    if isinstance(values, (str, bytes)):
        raise TypeError(
            f"{name} must be an iterable collection, not a string"
        )

    if not isinstance(values, Iterable):
        raise TypeError(f"{name} must be iterable")


def _build_formula_reference(
    sheet_name: str,
    cell_range: str,
) -> str:
    """
    Build a fully-qualified worksheet range reference.

    Examples
    --------
    >>> _build_formula_reference("Teams", "A2:A20")
    "Teams!$A$2:$A$20"

    >>> _build_formula_reference("Team List", "B2:B15")
    "'Team List'!$B$2:$B$15"

    Parameters
    ----------
    sheet_name:
        Worksheet name.

    cell_range:
        Excel range.

    Returns
    -------
    str
        Excel formula reference.
    """
    quoted = _quote_sheet_name(sheet_name)
    absolute = _absolute_range(cell_range)

    return f"{quoted}!{absolute}"


def _is_named_range(reference: str) -> bool:
    """
    Determine whether a string appears to be an Excel named range.

    This performs a lightweight syntactic check only.

    It does **not** verify existence within a workbook.

    Examples
    --------
    >>> _is_named_range("Teams")
    True

    >>> _is_named_range("A1:B10")
    False

    >>> _is_named_range("Sheet1!A1")
    False
    """
    if not isinstance(reference, str):
        return False

    reference = reference.strip()

    if not reference:
        return False

    try:
        range_boundaries(reference)
        return False
    except Exception:
        pass

    if "!" in reference:
        return False

    invalid = set(" :,$[](){}+-*/\\=")

    return not any(ch in invalid for ch in reference)


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "_quote_sheet_name",
        "_absolute_cell",
        "_absolute_range",
        "_column_letter",
        "_excel_list",
        "_escape_formula",
        "_validate_non_empty",
        "_validate_iterable",
        "_build_formula_reference",
        "_is_named_range",
    ]
)

###############################################################################
# Generic Validation Builders (Part 3A)
###############################################################################

from typing import Any


def _build_validation(
    *,
    validation_type: ValidationType,
    operator: Operator | None = None,
    formula1: FormulaValue | None = None,
    formula2: FormulaValue | None = None,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Construct and configure an ``openpyxl`` DataValidation object.

    This helper centralises all DataValidation construction used throughout
    the module. Every public validation builder should delegate object
    creation to this function to ensure deterministic behaviour and
    consistent configuration.

    Parameters
    ----------
    validation_type:
        Excel validation category.

    operator:
        Optional comparison operator.

    formula1:
        Primary comparison formula.

    formula2:
        Secondary comparison formula.

    allow_blank:
        Whether blank cells are permitted.

    prompt_title:
        Input message title.

    prompt_message:
        Input message displayed when the cell is selected.

    error_title:
        Error dialog title.

    error_message:
        Error dialog text.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Fully configured validation object.

    Notes
    -----
    This function intentionally does not attach the validation to any cells.
    Workbook integration is handled later by dedicated helper functions.
    """
    validation = DataValidation(
        type=validation_type.value,
        allowBlank=allow_blank,
    )

    if operator is not None:
        validation.operator = operator.value

    if formula1 is not None:
        if isinstance(formula1, str):
            formula1 = _escape_formula(formula1)
        validation.formula1 = formula1

    if formula2 is not None:
        if isinstance(formula2, str):
            formula2 = _escape_formula(formula2)
        validation.formula2 = formula2

    validation.promptTitle = prompt_title
    validation.prompt = prompt_message

    validation.errorTitle = error_title
    validation.error = error_message

    validation.showInputMessage = DEFAULT_SHOW_INPUT_MESSAGE
    validation.showErrorMessage = DEFAULT_SHOW_ERROR_MESSAGE

    validation.errorStyle = error_style.value

    return validation


def integer_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create an integer (whole number) validation.

    Parameters
    ----------
    minimum:
        Lower bound.

    maximum:
        Upper bound.

    operator:
        Excel comparison operator.

    allow_blank:
        Whether blank cells are allowed.

    prompt_title, prompt_message:
        Input message configuration.

    error_title, error_message:
        Error dialog configuration.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Configured validation object.

    Notes
    -----
    The meaning of ``minimum`` and ``maximum`` depends on the selected
    operator.

    Examples
    --------
    ::

        integer_validation(
            minimum=0,
            maximum=10
        )

        integer_validation(
            operator=Operator.GREATER_THAN,
            minimum=0
        )
    """
    if minimum is not None and not isinstance(minimum, int):
        raise TypeError("minimum must be an integer")

    if maximum is not None and not isinstance(maximum, int):
        raise TypeError("maximum must be an integer")

    if (
        operator == Operator.BETWEEN
        and minimum is not None
        and maximum is not None
        and minimum > maximum
    ):
        raise ValueError(
            "minimum cannot be greater than maximum"
        )

    return _build_validation(
        validation_type=ValidationType.WHOLE,
        operator=operator,
        formula1=minimum,
        formula2=maximum,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def whole_number_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a whole-number validation.

    This function is an explicit semantic alias of
    :func:`integer_validation`.

    The alias improves readability in workbook-generation code while
    keeping all implementation logic in a single location.

    Returns
    -------
    DataValidation
        Configured validation object.
    """
    return integer_validation(
        minimum=minimum,
        maximum=maximum,
        operator=operator,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def decimal_validation(
    *,
    minimum: Number | None = None,
    maximum: Number | None = None,
    operator: Operator = Operator.BETWEEN,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a decimal-number validation.

    Unlike integer validation, decimal validation accepts both integer
    and floating-point values.

    Parameters
    ----------
    minimum:
        Lower numeric bound.

    maximum:
        Upper numeric bound.

    operator:
        Excel comparison operator.

    allow_blank:
        Whether blank cells are permitted.

    Returns
    -------
    DataValidation
        Configured validation object.

    Examples
    --------
    ::

        decimal_validation(
            minimum=0.0,
            maximum=100.0
        )

        decimal_validation(
            operator=Operator.LESS_THAN,
            maximum=1.5
        )
    """
    if minimum is not None and not isinstance(minimum, (int, float)):
        raise TypeError(
            "minimum must be numeric"
        )

    if maximum is not None and not isinstance(maximum, (int, float)):
        raise TypeError(
            "maximum must be numeric"
        )

    if (
        operator == Operator.BETWEEN
        and minimum is not None
        and maximum is not None
        and minimum > maximum
    ):
        raise ValueError(
            "minimum cannot exceed maximum"
        )

    return _build_validation(
        validation_type=ValidationType.DECIMAL,
        operator=operator,
        formula1=minimum,
        formula2=maximum,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


###############################################################################
# Dropdown Validation Builders (Part 4A)
###############################################################################

def list_validation(
    values: StringCollection,
    *,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create an Excel dropdown validation from an explicit list of values.

    This function is intended for relatively small lists that can be embedded
    directly into the validation formula.

    Excel stores explicit dropdowns as a quoted comma-separated string, for
    example::

        "Yes,No"

    Unfortunately Excel limits this string to approximately 255 characters.
    Longer lists must instead be stored in worksheet cells and referenced via
    a worksheet range or named range.

    Parameters
    ----------
    values:
        Sequence of dropdown values.

    allow_blank:
        Whether blank cells are permitted.

    prompt_title:
        Input prompt title.

    prompt_message:
        Input prompt message.

    error_title:
        Error dialog title.

    error_message:
        Error dialog message.

    error_style:
        Excel validation error style.

    Returns
    -------
    DataValidation
        Configured list validation.

    Raises
    ------
    TypeError
        If values is not an iterable collection.

    ValueError
        If the collection is empty.

    ValueError
        If the combined explicit list exceeds Excel's inline limit.

    Notes
    -----
    This function intentionally raises an exception for oversized lists rather
    than silently converting them into worksheet-based dropdowns. Workbook
    generation should explicitly decide where long lists are stored.
    """
    _validate_iterable(values, "values")

    cleaned: list[str] = []

    for value in values:
        text = str(value).strip()

        if not text:
            raise ValueError(
                "Dropdown values cannot contain empty strings."
            )

        if "," in text:
            raise ValueError(
                "Dropdown values cannot contain commas "
                "when using explicit Excel lists."
            )

        cleaned.append(text)

    formula = _excel_list(cleaned)

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=formula,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def range_validation(
    *,
    sheet_name: str,
    cell_range: str,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation using a worksheet range.

    Examples
    --------
    ::

        range_validation(
            sheet_name="Lookup",
            cell_range="A2:A20",
        )

    Generates a validation referencing::

        Lookup!$A$2:$A$20

    If the worksheet name contains spaces or special characters it is
    automatically quoted.

    Parameters
    ----------
    sheet_name:
        Worksheet containing the dropdown values.

    cell_range:
        Excel range containing dropdown values.

    allow_blank:
        Whether blank values are permitted.

    Returns
    -------
    DataValidation
        Configured validation object.

    Notes
    -----
    This function performs only syntactic validation.

    It does not verify that the worksheet or cells actually exist.
    """
    reference = _build_formula_reference(
        sheet_name=sheet_name,
        cell_range=cell_range,
    )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=reference,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


def named_range_validation(
    named_range: str,
    *,
    allow_blank: bool = DEFAULT_ALLOW_BLANK,
    prompt_title: str = DEFAULT_PROMPT_TITLE,
    prompt_message: str = DEFAULT_PROMPT_MESSAGE,
    error_title: str = DEFAULT_ERROR_TITLE,
    error_message: str = DEFAULT_ERROR_MESSAGE,
    error_style: ErrorStyle = ErrorStyle.STOP,
) -> DataValidation:
    """
    Create a dropdown validation using an Excel named range.

    Named ranges are the preferred approach for large dropdowns because they

    * avoid Excel's 255-character explicit-list limitation,
    * automatically adapt when workbook layout changes,
    * improve readability of workbook formulas,
    * allow dynamic dropdowns.

    Parameters
    ----------
    named_range:
        Excel defined name.

    allow_blank:
        Whether blank values are allowed.

    prompt_title:
        Input prompt title.

    prompt_message:
        Input prompt.

    error_title:
        Error dialog title.

    error_message:
        Error dialog text.

    error_style:
        Excel error style.

    Returns
    -------
    DataValidation
        Configured dropdown validation.

    Raises
    ------
    ValueError
        If the supplied name is not a syntactically valid Excel defined name.

    Examples
    --------
    ::

        named_range_validation("Teams")

        named_range_validation("PlayerNames")

    Notes
    -----
    This function validates only the syntax of the supplied name.

    Existence of the named range is verified later when the workbook is
    generated.
    """
    _validate_non_empty(named_range, "named_range")

    if not _is_named_range(named_range):
        raise ValueError(
            f"'{named_range}' is not a valid Excel named range."
        )

    return _build_validation(
        validation_type=ValidationType.LIST,
        formula1=named_range,
        allow_blank=allow_blank,
        prompt_title=prompt_title,
        prompt_message=prompt_message,
        error_title=error_title,
        error_message=error_message,
        error_style=error_style,
    )


###############################################################################
# Update Public API
###############################################################################

__all__.extend(
    [
        "list_validation",
        "range_validation",
        "named_range_validation",
    ]
)